-- tests/mock_api/test_createavionics.lua
-- GENERATED completeness tests for mock_api/createavionics.lua (from api-docs inventory).
-- Regenerate with gen_tests.py. Every peripheral type must exist, expose its
-- documented methods, and each method must be callable with no arguments.
-- Methods with deterministic stub defaults additionally assert return types.

package.path = package.path .. ";./?.lua"

local assert = require("tests.helpers.assert")
local mod = require("mock_api.createavionics")

local suite = assert.suite("createavionics")

suite:test("type Create_CreativeMotor exists", function()
    assert.assertType(mod.types["Create_CreativeMotor"], "table")
end)
suite:test("Create_CreativeMotor exposes 12 methods", function()
    local methods = mod.types["Create_CreativeMotor"]
    assert.assertHasFunction(methods, "getGeneratedSpeed")
    assert.assertHasFunction(methods, "getKind")
    assert.assertHasFunction(methods, "getNetworkId")
    assert.assertHasFunction(methods, "getSelfId")
    assert.assertHasFunction(methods, "getSourceId")
    assert.assertHasFunction(methods, "getSpeed")
    assert.assertHasFunction(methods, "getStressContribution")
    assert.assertHasFunction(methods, "getStressImpact")
    assert.assertHasFunction(methods, "getSubnetworkAnchorId")
    assert.assertHasFunction(methods, "hasSource")
    assert.assertHasFunction(methods, "isOverstressed")
    assert.assertHasFunction(methods, "setGeneratedSpeed")
end)
suite:test("Create_CreativeMotor methods are callable", function()
    local methods = mod.types["Create_CreativeMotor"]
    assert.assertCalls(methods["getGeneratedSpeed"])
    assert.assertCalls(methods["getKind"])
    assert.assertCalls(methods["getNetworkId"])
    assert.assertCalls(methods["getSelfId"])
    assert.assertCalls(methods["getSourceId"])
    assert.assertCalls(methods["getSpeed"])
    assert.assertCalls(methods["getStressContribution"])
    assert.assertCalls(methods["getStressImpact"])
    assert.assertCalls(methods["getSubnetworkAnchorId"])
    assert.assertCalls(methods["hasSource"])
    assert.assertCalls(methods["isOverstressed"])
    assert.assertCalls(methods["setGeneratedSpeed"])
end)
suite:test("Create_CreativeMotor stub return types", function()
    local methods = mod.types["Create_CreativeMotor"]
    assert.assertType(methods["getGeneratedSpeed"](), "number")
    assert.assertType(methods["getKind"](), "string")
    assert.assertType(methods["getNetworkId"](), "string")
    assert.assertType(methods["getSelfId"](), "string")
    assert.assertType(methods["getSourceId"](), "string")
    assert.assertType(methods["getSpeed"](), "number")
    assert.assertType(methods["getStressContribution"](), "number")
    assert.assertType(methods["getStressImpact"](), "number")
    assert.assertType(methods["getSubnetworkAnchorId"](), "string")
    assert.assertType(methods["hasSource"](), "boolean")
    assert.assertType(methods["isOverstressed"](), "boolean")
end)
suite:test("type Create_ElevatorContact exists", function()
    assert.assertType(mod.types["Create_ElevatorContact"], "table")
end)
suite:test("Create_ElevatorContact exposes 14 methods", function()
    local methods = mod.types["Create_ElevatorContact"]
    assert.assertHasFunction(methods, "call")
    assert.assertHasFunction(methods, "getColumnId")
    assert.assertHasFunction(methods, "getDoorMode")
    assert.assertHasFunction(methods, "getLastReportedFloor")
    assert.assertHasFunction(methods, "getLongName")
    assert.assertHasFunction(methods, "getSelfId")
    assert.assertHasFunction(methods, "getShortName")
    assert.assertHasFunction(methods, "getY")
    assert.assertHasFunction(methods, "isCalling")
    assert.assertHasFunction(methods, "isPowered")
    assert.assertHasFunction(methods, "isPowering")
    assert.assertHasFunction(methods, "setDoorMode")
    assert.assertHasFunction(methods, "setLongName")
    assert.assertHasFunction(methods, "setShortName")
end)
suite:test("Create_ElevatorContact methods are callable", function()
    local methods = mod.types["Create_ElevatorContact"]
    assert.assertCalls(methods["call"])
    assert.assertCalls(methods["getColumnId"])
    assert.assertCalls(methods["getDoorMode"])
    assert.assertCalls(methods["getLastReportedFloor"])
    assert.assertCalls(methods["getLongName"])
    assert.assertCalls(methods["getSelfId"])
    assert.assertCalls(methods["getShortName"])
    assert.assertCalls(methods["getY"])
    assert.assertCalls(methods["isCalling"])
    assert.assertCalls(methods["isPowered"])
    assert.assertCalls(methods["isPowering"])
    assert.assertCalls(methods["setDoorMode"])
    assert.assertCalls(methods["setLongName"])
    assert.assertCalls(methods["setShortName"])
end)
suite:test("Create_ElevatorContact stub return types", function()
    local methods = mod.types["Create_ElevatorContact"]
    assert.assertType(methods["getColumnId"](), "string")
    assert.assertType(methods["getDoorMode"](), "string")
    assert.assertType(methods["getLastReportedFloor"](), "string")
    assert.assertType(methods["getLongName"](), "string")
    assert.assertType(methods["getSelfId"](), "string")
    assert.assertType(methods["getShortName"](), "string")
    assert.assertType(methods["getY"](), "number")
    assert.assertType(methods["isCalling"](), "boolean")
    assert.assertType(methods["isPowered"](), "boolean")
    assert.assertType(methods["isPowering"](), "boolean")
end)
suite:test("type Create_ElevatorPulley exists", function()
    assert.assertType(mod.types["Create_ElevatorPulley"], "table")
end)
suite:test("Create_ElevatorPulley exposes 27 methods", function()
    local methods = mod.types["Create_ElevatorPulley"]
    assert.assertHasFunction(methods, "assemble")
    assert.assertHasFunction(methods, "disassemble")
    assert.assertHasFunction(methods, "getColumnId")
    assert.assertHasFunction(methods, "getContraption")
    assert.assertHasFunction(methods, "getCurrentTargetY")
    assert.assertHasFunction(methods, "getCurrentY")
    assert.assertHasFunction(methods, "getItemLimit")
    assert.assertHasFunction(methods, "getKind")
    assert.assertHasFunction(methods, "getLastAssemblyError")
    assert.assertHasFunction(methods, "getMaxLength")
    assert.assertHasFunction(methods, "getMovementSpeed")
    assert.assertHasFunction(methods, "getNetworkId")
    assert.assertHasFunction(methods, "getOffset")
    assert.assertHasFunction(methods, "getSelfId")
    assert.assertHasFunction(methods, "getSourceId")
    assert.assertHasFunction(methods, "getSpeed")
    assert.assertHasFunction(methods, "getStressContribution")
    assert.assertHasFunction(methods, "getStressImpact")
    assert.assertHasFunction(methods, "getSubnetworkAnchorId")
    assert.assertHasFunction(methods, "hasSource")
    assert.assertHasFunction(methods, "isArrived")
    assert.assertHasFunction(methods, "isAssembled")
    assert.assertHasFunction(methods, "isOverstressed")
    assert.assertHasFunction(methods, "setTargetFloor")
    assert.assertHasFunction(methods, "setTargetY")
    assert.assertHasFunction(methods, "size")
    assert.assertHasFunction(methods, "stop")
end)
suite:test("Create_ElevatorPulley methods are callable", function()
    local methods = mod.types["Create_ElevatorPulley"]
    assert.assertCalls(methods["assemble"])
    assert.assertCalls(methods["disassemble"])
    assert.assertCalls(methods["getColumnId"])
    assert.assertCalls(methods["getContraption"])
    assert.assertCalls(methods["getCurrentTargetY"])
    assert.assertCalls(methods["getCurrentY"])
    assert.assertCalls(methods["getItemLimit"])
    assert.assertCalls(methods["getKind"])
    assert.assertCalls(methods["getLastAssemblyError"])
    assert.assertCalls(methods["getMaxLength"])
    assert.assertCalls(methods["getMovementSpeed"])
    assert.assertCalls(methods["getNetworkId"])
    assert.assertCalls(methods["getOffset"])
    assert.assertCalls(methods["getSelfId"])
    assert.assertCalls(methods["getSourceId"])
    assert.assertCalls(methods["getSpeed"])
    assert.assertCalls(methods["getStressContribution"])
    assert.assertCalls(methods["getStressImpact"])
    assert.assertCalls(methods["getSubnetworkAnchorId"])
    assert.assertCalls(methods["hasSource"])
    assert.assertCalls(methods["isArrived"])
    assert.assertCalls(methods["isAssembled"])
    assert.assertCalls(methods["isOverstressed"])
    assert.assertCalls(methods["setTargetFloor"])
    assert.assertCalls(methods["setTargetY"])
    assert.assertCalls(methods["size"])
    assert.assertCalls(methods["stop"])
end)
suite:test("Create_ElevatorPulley stub return types", function()
    local methods = mod.types["Create_ElevatorPulley"]
    assert.assertType(methods["getColumnId"](), "string")
    assert.assertType(methods["getCurrentTargetY"](), "number")
    assert.assertType(methods["getCurrentY"](), "number")
    assert.assertType(methods["getItemLimit"](), "number")
    assert.assertType(methods["getKind"](), "string")
    assert.assertType(methods["getLastAssemblyError"](), "string")
    assert.assertType(methods["getMaxLength"](), "number")
    assert.assertType(methods["getMovementSpeed"](), "number")
    assert.assertType(methods["getNetworkId"](), "string")
    assert.assertType(methods["getOffset"](), "number")
    assert.assertType(methods["getSelfId"](), "string")
    assert.assertType(methods["getSourceId"](), "string")
    assert.assertType(methods["getSpeed"](), "number")
    assert.assertType(methods["getStressContribution"](), "number")
    assert.assertType(methods["getStressImpact"](), "number")
    assert.assertType(methods["getSubnetworkAnchorId"](), "string")
    assert.assertType(methods["hasSource"](), "boolean")
    assert.assertType(methods["isArrived"](), "boolean")
    assert.assertType(methods["isAssembled"](), "boolean")
    assert.assertType(methods["isOverstressed"](), "boolean")
    assert.assertType(methods["size"](), "number")
end)
suite:test("type Create_GantryShaft exists", function()
    assert.assertType(mod.types["Create_GantryShaft"], "table")
end)
suite:test("Create_GantryShaft exposes 30 methods", function()
    local methods = mod.types["Create_GantryShaft"]
    assert.assertHasFunction(methods, "canAssembleOn")
    assert.assertHasFunction(methods, "disassemble")
    assert.assertHasFunction(methods, "getAxis")
    assert.assertHasFunction(methods, "getCarriage")
    assert.assertHasFunction(methods, "getCarriageId")
    assert.assertHasFunction(methods, "getCarriagePosition")
    assert.assertHasFunction(methods, "getContraption")
    assert.assertHasFunction(methods, "getItemLimit")
    assert.assertHasFunction(methods, "getKind")
    assert.assertHasFunction(methods, "getLastAssemblyError")
    assert.assertHasFunction(methods, "getMovementSpeed")
    assert.assertHasFunction(methods, "getNetworkId")
    assert.assertHasFunction(methods, "getPart")
    assert.assertHasFunction(methods, "getRailIndex")
    assert.assertHasFunction(methods, "getRailLength")
    assert.assertHasFunction(methods, "getRemainingMovement")
    assert.assertHasFunction(methods, "getSelfId")
    assert.assertHasFunction(methods, "getSourceId")
    assert.assertHasFunction(methods, "getSpeed")
    assert.assertHasFunction(methods, "getState")
    assert.assertHasFunction(methods, "getStressContribution")
    assert.assertHasFunction(methods, "getStressImpact")
    assert.assertHasFunction(methods, "getSubnetworkAnchorId")
    assert.assertHasFunction(methods, "hasCarriage")
    assert.assertHasFunction(methods, "hasSource")
    assert.assertHasFunction(methods, "isAssembled")
    assert.assertHasFunction(methods, "isOverstressed")
    assert.assertHasFunction(methods, "isPowered")
    assert.assertHasFunction(methods, "isStalled")
    assert.assertHasFunction(methods, "size")
end)
suite:test("Create_GantryShaft methods are callable", function()
    local methods = mod.types["Create_GantryShaft"]
    assert.assertCalls(methods["canAssembleOn"])
    assert.assertCalls(methods["disassemble"])
    assert.assertCalls(methods["getAxis"])
    assert.assertCalls(methods["getCarriage"])
    assert.assertCalls(methods["getCarriageId"])
    assert.assertCalls(methods["getCarriagePosition"])
    assert.assertCalls(methods["getContraption"])
    assert.assertCalls(methods["getItemLimit"])
    assert.assertCalls(methods["getKind"])
    assert.assertCalls(methods["getLastAssemblyError"])
    assert.assertCalls(methods["getMovementSpeed"])
    assert.assertCalls(methods["getNetworkId"])
    assert.assertCalls(methods["getPart"])
    assert.assertCalls(methods["getRailIndex"])
    assert.assertCalls(methods["getRailLength"])
    assert.assertCalls(methods["getRemainingMovement"])
    assert.assertCalls(methods["getSelfId"])
    assert.assertCalls(methods["getSourceId"])
    assert.assertCalls(methods["getSpeed"])
    assert.assertCalls(methods["getState"])
    assert.assertCalls(methods["getStressContribution"])
    assert.assertCalls(methods["getStressImpact"])
    assert.assertCalls(methods["getSubnetworkAnchorId"])
    assert.assertCalls(methods["hasCarriage"])
    assert.assertCalls(methods["hasSource"])
    assert.assertCalls(methods["isAssembled"])
    assert.assertCalls(methods["isOverstressed"])
    assert.assertCalls(methods["isPowered"])
    assert.assertCalls(methods["isStalled"])
    assert.assertCalls(methods["size"])
end)
suite:test("Create_GantryShaft stub return types", function()
    local methods = mod.types["Create_GantryShaft"]
    assert.assertType(methods["canAssembleOn"](), "boolean")
    assert.assertType(methods["getAxis"](), "string")
    assert.assertType(methods["getCarriageId"](), "string")
    assert.assertType(methods["getCarriagePosition"](), "number")
    assert.assertType(methods["getItemLimit"](), "number")
    assert.assertType(methods["getKind"](), "string")
    assert.assertType(methods["getLastAssemblyError"](), "string")
    assert.assertType(methods["getMovementSpeed"](), "number")
    assert.assertType(methods["getNetworkId"](), "string")
    assert.assertType(methods["getPart"](), "string")
    assert.assertType(methods["getRailIndex"](), "number")
    assert.assertType(methods["getRailLength"](), "number")
    assert.assertType(methods["getRemainingMovement"](), "number")
    assert.assertType(methods["getSelfId"](), "string")
    assert.assertType(methods["getSourceId"](), "string")
    assert.assertType(methods["getSpeed"](), "number")
    assert.assertType(methods["getState"](), "string")
    assert.assertType(methods["getStressContribution"](), "number")
    assert.assertType(methods["getStressImpact"](), "number")
    assert.assertType(methods["getSubnetworkAnchorId"](), "string")
    assert.assertType(methods["hasCarriage"](), "boolean")
    assert.assertType(methods["hasSource"](), "boolean")
    assert.assertType(methods["isAssembled"](), "boolean")
    assert.assertType(methods["isOverstressed"](), "boolean")
    assert.assertType(methods["isPowered"](), "boolean")
    assert.assertType(methods["isStalled"](), "boolean")
    assert.assertType(methods["size"](), "number")
end)
suite:test("type Create_MechanicalBearing exists", function()
    assert.assertType(mod.types["Create_MechanicalBearing"], "table")
end)
suite:test("Create_MechanicalBearing exposes 24 methods", function()
    local methods = mod.types["Create_MechanicalBearing"]
    assert.assertHasFunction(methods, "assemble")
    assert.assertHasFunction(methods, "disassemble")
    assert.assertHasFunction(methods, "getAngle")
    assert.assertHasFunction(methods, "getAngleRad")
    assert.assertHasFunction(methods, "getAngularSpeed")
    assert.assertHasFunction(methods, "getContraption")
    assert.assertHasFunction(methods, "getItemLimit")
    assert.assertHasFunction(methods, "getKind")
    assert.assertHasFunction(methods, "getLastAssemblyError")
    assert.assertHasFunction(methods, "getNetworkId")
    assert.assertHasFunction(methods, "getRotationMode")
    assert.assertHasFunction(methods, "getSelfId")
    assert.assertHasFunction(methods, "getSourceId")
    assert.assertHasFunction(methods, "getSpeed")
    assert.assertHasFunction(methods, "getStressContribution")
    assert.assertHasFunction(methods, "getStressImpact")
    assert.assertHasFunction(methods, "getSubnetworkAnchorId")
    assert.assertHasFunction(methods, "hasSource")
    assert.assertHasFunction(methods, "isAssembled")
    assert.assertHasFunction(methods, "isNearInitialAngle")
    assert.assertHasFunction(methods, "isOverstressed")
    assert.assertHasFunction(methods, "isWoodenTop")
    assert.assertHasFunction(methods, "setRotationMode")
    assert.assertHasFunction(methods, "size")
end)
suite:test("Create_MechanicalBearing methods are callable", function()
    local methods = mod.types["Create_MechanicalBearing"]
    assert.assertCalls(methods["assemble"])
    assert.assertCalls(methods["disassemble"])
    assert.assertCalls(methods["getAngle"])
    assert.assertCalls(methods["getAngleRad"])
    assert.assertCalls(methods["getAngularSpeed"])
    assert.assertCalls(methods["getContraption"])
    assert.assertCalls(methods["getItemLimit"])
    assert.assertCalls(methods["getKind"])
    assert.assertCalls(methods["getLastAssemblyError"])
    assert.assertCalls(methods["getNetworkId"])
    assert.assertCalls(methods["getRotationMode"])
    assert.assertCalls(methods["getSelfId"])
    assert.assertCalls(methods["getSourceId"])
    assert.assertCalls(methods["getSpeed"])
    assert.assertCalls(methods["getStressContribution"])
    assert.assertCalls(methods["getStressImpact"])
    assert.assertCalls(methods["getSubnetworkAnchorId"])
    assert.assertCalls(methods["hasSource"])
    assert.assertCalls(methods["isAssembled"])
    assert.assertCalls(methods["isNearInitialAngle"])
    assert.assertCalls(methods["isOverstressed"])
    assert.assertCalls(methods["isWoodenTop"])
    assert.assertCalls(methods["setRotationMode"])
    assert.assertCalls(methods["size"])
end)
suite:test("Create_MechanicalBearing stub return types", function()
    local methods = mod.types["Create_MechanicalBearing"]
    assert.assertType(methods["getAngle"](), "number")
    assert.assertType(methods["getAngleRad"](), "number")
    assert.assertType(methods["getAngularSpeed"](), "number")
    assert.assertType(methods["getItemLimit"](), "number")
    assert.assertType(methods["getKind"](), "string")
    assert.assertType(methods["getLastAssemblyError"](), "string")
    assert.assertType(methods["getNetworkId"](), "string")
    assert.assertType(methods["getRotationMode"](), "string")
    assert.assertType(methods["getSelfId"](), "string")
    assert.assertType(methods["getSourceId"](), "string")
    assert.assertType(methods["getSpeed"](), "number")
    assert.assertType(methods["getStressContribution"](), "number")
    assert.assertType(methods["getStressImpact"](), "number")
    assert.assertType(methods["getSubnetworkAnchorId"](), "string")
    assert.assertType(methods["hasSource"](), "boolean")
    assert.assertType(methods["isAssembled"](), "boolean")
    assert.assertType(methods["isNearInitialAngle"](), "boolean")
    assert.assertType(methods["isOverstressed"](), "boolean")
    assert.assertType(methods["isWoodenTop"](), "boolean")
    assert.assertType(methods["size"](), "number")
end)
suite:test("type Create_MechanicalPiston exists", function()
    assert.assertType(mod.types["Create_MechanicalPiston"], "table")
end)
suite:test("Create_MechanicalPiston exposes 24 methods", function()
    local methods = mod.types["Create_MechanicalPiston"]
    assert.assertHasFunction(methods, "assemble")
    assert.assertHasFunction(methods, "disassemble")
    assert.assertHasFunction(methods, "getContraption")
    assert.assertHasFunction(methods, "getItemLimit")
    assert.assertHasFunction(methods, "getKind")
    assert.assertHasFunction(methods, "getLastAssemblyError")
    assert.assertHasFunction(methods, "getMotionVector")
    assert.assertHasFunction(methods, "getMovementMode")
    assert.assertHasFunction(methods, "getMovementSpeed")
    assert.assertHasFunction(methods, "getNetworkId")
    assert.assertHasFunction(methods, "getOffset")
    assert.assertHasFunction(methods, "getSelfId")
    assert.assertHasFunction(methods, "getSourceId")
    assert.assertHasFunction(methods, "getSpeed")
    assert.assertHasFunction(methods, "getState")
    assert.assertHasFunction(methods, "getStressContribution")
    assert.assertHasFunction(methods, "getStressImpact")
    assert.assertHasFunction(methods, "getSubnetworkAnchorId")
    assert.assertHasFunction(methods, "hasSource")
    assert.assertHasFunction(methods, "isAssembled")
    assert.assertHasFunction(methods, "isOverstressed")
    assert.assertHasFunction(methods, "isSticky")
    assert.assertHasFunction(methods, "setMovementMode")
    assert.assertHasFunction(methods, "size")
end)
suite:test("Create_MechanicalPiston methods are callable", function()
    local methods = mod.types["Create_MechanicalPiston"]
    assert.assertCalls(methods["assemble"])
    assert.assertCalls(methods["disassemble"])
    assert.assertCalls(methods["getContraption"])
    assert.assertCalls(methods["getItemLimit"])
    assert.assertCalls(methods["getKind"])
    assert.assertCalls(methods["getLastAssemblyError"])
    assert.assertCalls(methods["getMotionVector"])
    assert.assertCalls(methods["getMovementMode"])
    assert.assertCalls(methods["getMovementSpeed"])
    assert.assertCalls(methods["getNetworkId"])
    assert.assertCalls(methods["getOffset"])
    assert.assertCalls(methods["getSelfId"])
    assert.assertCalls(methods["getSourceId"])
    assert.assertCalls(methods["getSpeed"])
    assert.assertCalls(methods["getState"])
    assert.assertCalls(methods["getStressContribution"])
    assert.assertCalls(methods["getStressImpact"])
    assert.assertCalls(methods["getSubnetworkAnchorId"])
    assert.assertCalls(methods["hasSource"])
    assert.assertCalls(methods["isAssembled"])
    assert.assertCalls(methods["isOverstressed"])
    assert.assertCalls(methods["isSticky"])
    assert.assertCalls(methods["setMovementMode"])
    assert.assertCalls(methods["size"])
end)
suite:test("Create_MechanicalPiston stub return types", function()
    local methods = mod.types["Create_MechanicalPiston"]
    assert.assertType(methods["getItemLimit"](), "number")
    assert.assertType(methods["getKind"](), "string")
    assert.assertType(methods["getLastAssemblyError"](), "string")
    assert.assertType(methods["getMotionVector"](), "table")
    assert.assertType(methods["getMovementMode"](), "string")
    assert.assertType(methods["getMovementSpeed"](), "number")
    assert.assertType(methods["getNetworkId"](), "string")
    assert.assertType(methods["getOffset"](), "number")
    assert.assertType(methods["getSelfId"](), "string")
    assert.assertType(methods["getSourceId"](), "string")
    assert.assertType(methods["getSpeed"](), "number")
    assert.assertType(methods["getState"](), "string")
    assert.assertType(methods["getStressContribution"](), "number")
    assert.assertType(methods["getStressImpact"](), "number")
    assert.assertType(methods["getSubnetworkAnchorId"](), "string")
    assert.assertType(methods["hasSource"](), "boolean")
    assert.assertType(methods["isAssembled"](), "boolean")
    assert.assertType(methods["isOverstressed"](), "boolean")
    assert.assertType(methods["isSticky"](), "boolean")
    assert.assertType(methods["size"](), "number")
end)
suite:test("type Create_RopePulley exists", function()
    assert.assertType(mod.types["Create_RopePulley"], "table")
end)
suite:test("Create_RopePulley exposes 26 methods", function()
    local methods = mod.types["Create_RopePulley"]
    assert.assertHasFunction(methods, "assemble")
    assert.assertHasFunction(methods, "disassemble")
    assert.assertHasFunction(methods, "getContraption")
    assert.assertHasFunction(methods, "getCurrentY")
    assert.assertHasFunction(methods, "getItemLimit")
    assert.assertHasFunction(methods, "getKind")
    assert.assertHasFunction(methods, "getLastAssemblyError")
    assert.assertHasFunction(methods, "getMaxLength")
    assert.assertHasFunction(methods, "getMirrorParentId")
    assert.assertHasFunction(methods, "getMotionVector")
    assert.assertHasFunction(methods, "getMovementMode")
    assert.assertHasFunction(methods, "getMovementSpeed")
    assert.assertHasFunction(methods, "getNetworkId")
    assert.assertHasFunction(methods, "getOffset")
    assert.assertHasFunction(methods, "getSelfId")
    assert.assertHasFunction(methods, "getSourceId")
    assert.assertHasFunction(methods, "getSpeed")
    assert.assertHasFunction(methods, "getStressContribution")
    assert.assertHasFunction(methods, "getStressImpact")
    assert.assertHasFunction(methods, "getSubnetworkAnchorId")
    assert.assertHasFunction(methods, "hasSource")
    assert.assertHasFunction(methods, "isAssembled")
    assert.assertHasFunction(methods, "isMirrorChild")
    assert.assertHasFunction(methods, "isOverstressed")
    assert.assertHasFunction(methods, "setMovementMode")
    assert.assertHasFunction(methods, "size")
end)
suite:test("Create_RopePulley methods are callable", function()
    local methods = mod.types["Create_RopePulley"]
    assert.assertCalls(methods["assemble"])
    assert.assertCalls(methods["disassemble"])
    assert.assertCalls(methods["getContraption"])
    assert.assertCalls(methods["getCurrentY"])
    assert.assertCalls(methods["getItemLimit"])
    assert.assertCalls(methods["getKind"])
    assert.assertCalls(methods["getLastAssemblyError"])
    assert.assertCalls(methods["getMaxLength"])
    assert.assertCalls(methods["getMirrorParentId"])
    assert.assertCalls(methods["getMotionVector"])
    assert.assertCalls(methods["getMovementMode"])
    assert.assertCalls(methods["getMovementSpeed"])
    assert.assertCalls(methods["getNetworkId"])
    assert.assertCalls(methods["getOffset"])
    assert.assertCalls(methods["getSelfId"])
    assert.assertCalls(methods["getSourceId"])
    assert.assertCalls(methods["getSpeed"])
    assert.assertCalls(methods["getStressContribution"])
    assert.assertCalls(methods["getStressImpact"])
    assert.assertCalls(methods["getSubnetworkAnchorId"])
    assert.assertCalls(methods["hasSource"])
    assert.assertCalls(methods["isAssembled"])
    assert.assertCalls(methods["isMirrorChild"])
    assert.assertCalls(methods["isOverstressed"])
    assert.assertCalls(methods["setMovementMode"])
    assert.assertCalls(methods["size"])
end)
suite:test("Create_RopePulley stub return types", function()
    local methods = mod.types["Create_RopePulley"]
    assert.assertType(methods["getCurrentY"](), "number")
    assert.assertType(methods["getItemLimit"](), "number")
    assert.assertType(methods["getKind"](), "string")
    assert.assertType(methods["getLastAssemblyError"](), "string")
    assert.assertType(methods["getMaxLength"](), "number")
    assert.assertType(methods["getMirrorParentId"](), "string")
    assert.assertType(methods["getMotionVector"](), "table")
    assert.assertType(methods["getMovementMode"](), "string")
    assert.assertType(methods["getMovementSpeed"](), "number")
    assert.assertType(methods["getNetworkId"](), "string")
    assert.assertType(methods["getOffset"](), "number")
    assert.assertType(methods["getSelfId"](), "string")
    assert.assertType(methods["getSourceId"](), "string")
    assert.assertType(methods["getSpeed"](), "number")
    assert.assertType(methods["getStressContribution"](), "number")
    assert.assertType(methods["getStressImpact"](), "number")
    assert.assertType(methods["getSubnetworkAnchorId"](), "string")
    assert.assertType(methods["hasSource"](), "boolean")
    assert.assertType(methods["isAssembled"](), "boolean")
    assert.assertType(methods["isMirrorChild"](), "boolean")
    assert.assertType(methods["isOverstressed"](), "boolean")
    assert.assertType(methods["size"](), "number")
end)
suite:test("type Create_RotationSpeedController exists", function()
    assert.assertType(mod.types["Create_RotationSpeedController"], "table")
end)
suite:test("Create_RotationSpeedController exposes 12 methods", function()
    local methods = mod.types["Create_RotationSpeedController"]
    assert.assertHasFunction(methods, "getKind")
    assert.assertHasFunction(methods, "getNetworkId")
    assert.assertHasFunction(methods, "getSelfId")
    assert.assertHasFunction(methods, "getSourceId")
    assert.assertHasFunction(methods, "getSpeed")
    assert.assertHasFunction(methods, "getStressContribution")
    assert.assertHasFunction(methods, "getStressImpact")
    assert.assertHasFunction(methods, "getSubnetworkAnchorId")
    assert.assertHasFunction(methods, "getTargetSpeed")
    assert.assertHasFunction(methods, "hasSource")
    assert.assertHasFunction(methods, "isOverstressed")
    assert.assertHasFunction(methods, "setTargetSpeed")
end)
suite:test("Create_RotationSpeedController methods are callable", function()
    local methods = mod.types["Create_RotationSpeedController"]
    assert.assertCalls(methods["getKind"])
    assert.assertCalls(methods["getNetworkId"])
    assert.assertCalls(methods["getSelfId"])
    assert.assertCalls(methods["getSourceId"])
    assert.assertCalls(methods["getSpeed"])
    assert.assertCalls(methods["getStressContribution"])
    assert.assertCalls(methods["getStressImpact"])
    assert.assertCalls(methods["getSubnetworkAnchorId"])
    assert.assertCalls(methods["getTargetSpeed"])
    assert.assertCalls(methods["hasSource"])
    assert.assertCalls(methods["isOverstressed"])
    assert.assertCalls(methods["setTargetSpeed"])
end)
suite:test("Create_RotationSpeedController stub return types", function()
    local methods = mod.types["Create_RotationSpeedController"]
    assert.assertType(methods["getKind"](), "string")
    assert.assertType(methods["getNetworkId"](), "string")
    assert.assertType(methods["getSelfId"](), "string")
    assert.assertType(methods["getSourceId"](), "string")
    assert.assertType(methods["getSpeed"](), "number")
    assert.assertType(methods["getStressContribution"](), "number")
    assert.assertType(methods["getStressImpact"](), "number")
    assert.assertType(methods["getSubnetworkAnchorId"](), "string")
    assert.assertType(methods["getTargetSpeed"](), "number")
    assert.assertType(methods["hasSource"](), "boolean")
    assert.assertType(methods["isOverstressed"](), "boolean")
end)
suite:test("type Create_Speedometer exists", function()
    assert.assertType(mod.types["Create_Speedometer"], "table")
end)
suite:test("Create_Speedometer exposes 10 methods", function()
    local methods = mod.types["Create_Speedometer"]
    assert.assertHasFunction(methods, "getKind")
    assert.assertHasFunction(methods, "getNetworkId")
    assert.assertHasFunction(methods, "getSelfId")
    assert.assertHasFunction(methods, "getSourceId")
    assert.assertHasFunction(methods, "getSpeed")
    assert.assertHasFunction(methods, "getStressContribution")
    assert.assertHasFunction(methods, "getStressImpact")
    assert.assertHasFunction(methods, "getSubnetworkAnchorId")
    assert.assertHasFunction(methods, "hasSource")
    assert.assertHasFunction(methods, "isOverstressed")
end)
suite:test("Create_Speedometer methods are callable", function()
    local methods = mod.types["Create_Speedometer"]
    assert.assertCalls(methods["getKind"])
    assert.assertCalls(methods["getNetworkId"])
    assert.assertCalls(methods["getSelfId"])
    assert.assertCalls(methods["getSourceId"])
    assert.assertCalls(methods["getSpeed"])
    assert.assertCalls(methods["getStressContribution"])
    assert.assertCalls(methods["getStressImpact"])
    assert.assertCalls(methods["getSubnetworkAnchorId"])
    assert.assertCalls(methods["hasSource"])
    assert.assertCalls(methods["isOverstressed"])
end)
suite:test("Create_Speedometer stub return types", function()
    local methods = mod.types["Create_Speedometer"]
    assert.assertType(methods["getKind"](), "string")
    assert.assertType(methods["getNetworkId"](), "string")
    assert.assertType(methods["getSelfId"](), "string")
    assert.assertType(methods["getSourceId"](), "string")
    assert.assertType(methods["getSpeed"](), "number")
    assert.assertType(methods["getStressContribution"](), "number")
    assert.assertType(methods["getStressImpact"](), "number")
    assert.assertType(methods["getSubnetworkAnchorId"](), "string")
    assert.assertType(methods["hasSource"](), "boolean")
    assert.assertType(methods["isOverstressed"](), "boolean")
end)
suite:test("type Create_Stressometer exists", function()
    assert.assertType(mod.types["Create_Stressometer"], "table")
end)
suite:test("Create_Stressometer exposes 12 methods", function()
    local methods = mod.types["Create_Stressometer"]
    assert.assertHasFunction(methods, "getKind")
    assert.assertHasFunction(methods, "getNetworkId")
    assert.assertHasFunction(methods, "getSelfId")
    assert.assertHasFunction(methods, "getSourceId")
    assert.assertHasFunction(methods, "getSpeed")
    assert.assertHasFunction(methods, "getStress")
    assert.assertHasFunction(methods, "getStressCapacity")
    assert.assertHasFunction(methods, "getStressContribution")
    assert.assertHasFunction(methods, "getStressImpact")
    assert.assertHasFunction(methods, "getSubnetworkAnchorId")
    assert.assertHasFunction(methods, "hasSource")
    assert.assertHasFunction(methods, "isOverstressed")
end)
suite:test("Create_Stressometer methods are callable", function()
    local methods = mod.types["Create_Stressometer"]
    assert.assertCalls(methods["getKind"])
    assert.assertCalls(methods["getNetworkId"])
    assert.assertCalls(methods["getSelfId"])
    assert.assertCalls(methods["getSourceId"])
    assert.assertCalls(methods["getSpeed"])
    assert.assertCalls(methods["getStress"])
    assert.assertCalls(methods["getStressCapacity"])
    assert.assertCalls(methods["getStressContribution"])
    assert.assertCalls(methods["getStressImpact"])
    assert.assertCalls(methods["getSubnetworkAnchorId"])
    assert.assertCalls(methods["hasSource"])
    assert.assertCalls(methods["isOverstressed"])
end)
suite:test("Create_Stressometer stub return types", function()
    local methods = mod.types["Create_Stressometer"]
    assert.assertType(methods["getKind"](), "string")
    assert.assertType(methods["getNetworkId"](), "string")
    assert.assertType(methods["getSelfId"](), "string")
    assert.assertType(methods["getSourceId"](), "string")
    assert.assertType(methods["getSpeed"](), "number")
    assert.assertType(methods["getStress"](), "number")
    assert.assertType(methods["getStressCapacity"](), "number")
    assert.assertType(methods["getStressContribution"](), "number")
    assert.assertType(methods["getStressImpact"](), "number")
    assert.assertType(methods["getSubnetworkAnchorId"](), "string")
    assert.assertType(methods["hasSource"](), "boolean")
    assert.assertType(methods["isOverstressed"](), "boolean")
end)
suite:test("type altitude_sensor exists", function()
    assert.assertType(mod.types["altitude_sensor"], "table")
end)
suite:test("altitude_sensor exposes 3 methods", function()
    local methods = mod.types["altitude_sensor"]
    assert.assertHasFunction(methods, "getAirPressure")
    assert.assertHasFunction(methods, "getHeight")
    assert.assertHasFunction(methods, "getVerticalSpeed")
end)
suite:test("altitude_sensor methods are callable", function()
    local methods = mod.types["altitude_sensor"]
    assert.assertCalls(methods["getAirPressure"])
    assert.assertCalls(methods["getHeight"])
    assert.assertCalls(methods["getVerticalSpeed"])
end)
suite:test("altitude_sensor stub return types", function()
    local methods = mod.types["altitude_sensor"]
    assert.assertType(methods["getAirPressure"](), "number")
    assert.assertType(methods["getHeight"](), "number")
    assert.assertType(methods["getVerticalSpeed"](), "number")
end)
suite:test("type analog_transmission exists", function()
    assert.assertType(mod.types["analog_transmission"], "table")
end)
suite:test("analog_transmission exposes 20 methods", function()
    local methods = mod.types["analog_transmission"]
    assert.assertHasFunction(methods, "getAxis")
    assert.assertHasFunction(methods, "getKind")
    assert.assertHasFunction(methods, "getNetworkId")
    assert.assertHasFunction(methods, "getOutputSpeed")
    assert.assertHasFunction(methods, "getOutputStressImpact")
    assert.assertHasFunction(methods, "getOutputTheoreticalSpeed")
    assert.assertHasFunction(methods, "getRotationModifier")
    assert.assertHasFunction(methods, "getSelfId")
    assert.assertHasFunction(methods, "getSignal")
    assert.assertHasFunction(methods, "getSourceId")
    assert.assertHasFunction(methods, "getSpeed")
    assert.assertHasFunction(methods, "getStressContribution")
    assert.assertHasFunction(methods, "getStressImpact")
    assert.assertHasFunction(methods, "getSubnetworkAnchorId")
    assert.assertHasFunction(methods, "hasSource")
    assert.assertHasFunction(methods, "isExternallyControlled")
    assert.assertHasFunction(methods, "isOversaturated")
    assert.assertHasFunction(methods, "isOverstressed")
    assert.assertHasFunction(methods, "releaseSignal")
    assert.assertHasFunction(methods, "setSignal")
end)
suite:test("analog_transmission methods are callable", function()
    local methods = mod.types["analog_transmission"]
    assert.assertCalls(methods["getAxis"])
    assert.assertCalls(methods["getKind"])
    assert.assertCalls(methods["getNetworkId"])
    assert.assertCalls(methods["getOutputSpeed"])
    assert.assertCalls(methods["getOutputStressImpact"])
    assert.assertCalls(methods["getOutputTheoreticalSpeed"])
    assert.assertCalls(methods["getRotationModifier"])
    assert.assertCalls(methods["getSelfId"])
    assert.assertCalls(methods["getSignal"])
    assert.assertCalls(methods["getSourceId"])
    assert.assertCalls(methods["getSpeed"])
    assert.assertCalls(methods["getStressContribution"])
    assert.assertCalls(methods["getStressImpact"])
    assert.assertCalls(methods["getSubnetworkAnchorId"])
    assert.assertCalls(methods["hasSource"])
    assert.assertCalls(methods["isExternallyControlled"])
    assert.assertCalls(methods["isOversaturated"])
    assert.assertCalls(methods["isOverstressed"])
    assert.assertCalls(methods["releaseSignal"])
    assert.assertCalls(methods["setSignal"])
end)
suite:test("analog_transmission stub return types", function()
    local methods = mod.types["analog_transmission"]
    assert.assertType(methods["getAxis"](), "string")
    assert.assertType(methods["getKind"](), "string")
    assert.assertType(methods["getNetworkId"](), "string")
    assert.assertType(methods["getOutputSpeed"](), "number")
    assert.assertType(methods["getOutputStressImpact"](), "number")
    assert.assertType(methods["getOutputTheoreticalSpeed"](), "number")
    assert.assertType(methods["getRotationModifier"](), "number")
    assert.assertType(methods["getSelfId"](), "string")
    assert.assertType(methods["getSignal"](), "number")
    assert.assertType(methods["getSourceId"](), "string")
    assert.assertType(methods["getSpeed"](), "number")
    assert.assertType(methods["getStressContribution"](), "number")
    assert.assertType(methods["getStressImpact"](), "number")
    assert.assertType(methods["getSubnetworkAnchorId"](), "string")
    assert.assertType(methods["hasSource"](), "boolean")
    assert.assertType(methods["isExternallyControlled"](), "boolean")
    assert.assertType(methods["isOversaturated"](), "boolean")
    assert.assertType(methods["isOverstressed"](), "boolean")
end)
suite:test("type directional_gearshift exists", function()
    assert.assertType(mod.types["directional_gearshift"], "table")
end)
suite:test("directional_gearshift exposes 14 methods", function()
    local methods = mod.types["directional_gearshift"]
    assert.assertHasFunction(methods, "getKind")
    assert.assertHasFunction(methods, "getMode")
    assert.assertHasFunction(methods, "getNetworkId")
    assert.assertHasFunction(methods, "getSelfId")
    assert.assertHasFunction(methods, "getSourceAxis")
    assert.assertHasFunction(methods, "getSourceId")
    assert.assertHasFunction(methods, "getSpeed")
    assert.assertHasFunction(methods, "getStressContribution")
    assert.assertHasFunction(methods, "getStressImpact")
    assert.assertHasFunction(methods, "getSubnetworkAnchorId")
    assert.assertHasFunction(methods, "hasSource")
    assert.assertHasFunction(methods, "isLeftPowered")
    assert.assertHasFunction(methods, "isOverstressed")
    assert.assertHasFunction(methods, "isRightPowered")
end)
suite:test("directional_gearshift methods are callable", function()
    local methods = mod.types["directional_gearshift"]
    assert.assertCalls(methods["getKind"])
    assert.assertCalls(methods["getMode"])
    assert.assertCalls(methods["getNetworkId"])
    assert.assertCalls(methods["getSelfId"])
    assert.assertCalls(methods["getSourceAxis"])
    assert.assertCalls(methods["getSourceId"])
    assert.assertCalls(methods["getSpeed"])
    assert.assertCalls(methods["getStressContribution"])
    assert.assertCalls(methods["getStressImpact"])
    assert.assertCalls(methods["getSubnetworkAnchorId"])
    assert.assertCalls(methods["hasSource"])
    assert.assertCalls(methods["isLeftPowered"])
    assert.assertCalls(methods["isOverstressed"])
    assert.assertCalls(methods["isRightPowered"])
end)
suite:test("directional_gearshift stub return types", function()
    local methods = mod.types["directional_gearshift"]
    assert.assertType(methods["getKind"](), "string")
    assert.assertType(methods["getMode"](), "string")
    assert.assertType(methods["getNetworkId"](), "string")
    assert.assertType(methods["getSelfId"](), "string")
    assert.assertType(methods["getSourceAxis"](), "string")
    assert.assertType(methods["getSourceId"](), "string")
    assert.assertType(methods["getSpeed"](), "number")
    assert.assertType(methods["getStressContribution"](), "number")
    assert.assertType(methods["getStressImpact"](), "number")
    assert.assertType(methods["getSubnetworkAnchorId"](), "string")
    assert.assertType(methods["hasSource"](), "boolean")
    assert.assertType(methods["isLeftPowered"](), "boolean")
    assert.assertType(methods["isOverstressed"](), "boolean")
    assert.assertType(methods["isRightPowered"](), "boolean")
end)
suite:test("type gas_provider exists", function()
    assert.assertType(mod.types["gas_provider"], "table")
end)
suite:test("gas_provider exposes 14 methods", function()
    local methods = mod.types["gas_provider"]
    assert.assertHasFunction(methods, "getBalloonCapacity")
    assert.assertHasFunction(methods, "getBalloonFilledVolume")
    assert.assertHasFunction(methods, "getBalloonHeight")
    assert.assertHasFunction(methods, "getBalloonLift")
    assert.assertHasFunction(methods, "getBalloonTargetVolume")
    assert.assertHasFunction(methods, "getBalloonVolumeChange")
    assert.assertHasFunction(methods, "getBoilerEfficiency")
    assert.assertHasFunction(methods, "getGasOutput")
    assert.assertHasFunction(methods, "getGasType")
    assert.assertHasFunction(methods, "getSignalStrength")
    assert.assertHasFunction(methods, "getTargetAmount")
    assert.assertHasFunction(methods, "hasBalloon")
    assert.assertHasFunction(methods, "isActive")
    assert.assertHasFunction(methods, "setTargetAmount")
end)
suite:test("gas_provider methods are callable", function()
    local methods = mod.types["gas_provider"]
    assert.assertCalls(methods["getBalloonCapacity"])
    assert.assertCalls(methods["getBalloonFilledVolume"])
    assert.assertCalls(methods["getBalloonHeight"])
    assert.assertCalls(methods["getBalloonLift"])
    assert.assertCalls(methods["getBalloonTargetVolume"])
    assert.assertCalls(methods["getBalloonVolumeChange"])
    assert.assertCalls(methods["getBoilerEfficiency"])
    assert.assertCalls(methods["getGasOutput"])
    assert.assertCalls(methods["getGasType"])
    assert.assertCalls(methods["getSignalStrength"])
    assert.assertCalls(methods["getTargetAmount"])
    assert.assertCalls(methods["hasBalloon"])
    assert.assertCalls(methods["isActive"])
    assert.assertCalls(methods["setTargetAmount"])
end)
suite:test("gas_provider stub return types", function()
    local methods = mod.types["gas_provider"]
    assert.assertType(methods["getBalloonCapacity"](), "number")
    assert.assertType(methods["getBalloonFilledVolume"](), "number")
    assert.assertType(methods["getBalloonHeight"](), "number")
    assert.assertType(methods["getBalloonLift"](), "number")
    assert.assertType(methods["getBalloonTargetVolume"](), "number")
    assert.assertType(methods["getBalloonVolumeChange"](), "number")
    assert.assertType(methods["getBoilerEfficiency"](), "number")
    assert.assertType(methods["getGasOutput"](), "number")
    assert.assertType(methods["getGasType"](), "string")
    assert.assertType(methods["getSignalStrength"](), "number")
    assert.assertType(methods["getTargetAmount"](), "number")
    assert.assertType(methods["hasBalloon"](), "boolean")
    assert.assertType(methods["isActive"](), "boolean")
end)
suite:test("type gimbal_sensor exists", function()
    assert.assertType(mod.types["gimbal_sensor"], "table")
end)
suite:test("gimbal_sensor exposes 6 methods", function()
    local methods = mod.types["gimbal_sensor"]
    assert.assertHasFunction(methods, "getAngles")
    assert.assertHasFunction(methods, "getAnglesRad")
    assert.assertHasFunction(methods, "getAngularRates")
    assert.assertHasFunction(methods, "getAngularRatesRad")
    assert.assertHasFunction(methods, "getGravity")
    assert.assertHasFunction(methods, "getLinearAcceleration")
end)
suite:test("gimbal_sensor methods are callable", function()
    local methods = mod.types["gimbal_sensor"]
    assert.assertCalls(methods["getAngles"])
    assert.assertCalls(methods["getAnglesRad"])
    assert.assertCalls(methods["getAngularRates"])
    assert.assertCalls(methods["getAngularRatesRad"])
    assert.assertCalls(methods["getGravity"])
    assert.assertCalls(methods["getLinearAcceleration"])
end)
suite:test("gimbal_sensor stub return types", function()
    local methods = mod.types["gimbal_sensor"]
    assert.assertType(methods["getAngles"](), "table")
    assert.assertType(methods["getAnglesRad"](), "table")
    assert.assertType(methods["getAngularRates"](), "table")
    assert.assertType(methods["getAngularRatesRad"](), "table")
    assert.assertType(methods["getGravity"](), "table")
    assert.assertType(methods["getLinearAcceleration"](), "table")
end)
suite:test("type gyroscopic_propeller_bearing exists", function()
    assert.assertType(mod.types["gyroscopic_propeller_bearing"], "table")
end)
suite:test("gyroscopic_propeller_bearing exposes 32 methods", function()
    local methods = mod.types["gyroscopic_propeller_bearing"]
    assert.assertHasFunction(methods, "assemble")
    assert.assertHasFunction(methods, "clearManualTarget")
    assert.assertHasFunction(methods, "disassemble")
    assert.assertHasFunction(methods, "getAirflow")
    assert.assertHasFunction(methods, "getAngle")
    assert.assertHasFunction(methods, "getAngularSpeed")
    assert.assertHasFunction(methods, "getAxis")
    assert.assertHasFunction(methods, "getBlockNormal")
    assert.assertHasFunction(methods, "getFacingVector")
    assert.assertHasFunction(methods, "getKind")
    assert.assertHasFunction(methods, "getManualTarget")
    assert.assertHasFunction(methods, "getNetworkId")
    assert.assertHasFunction(methods, "getRotationSpeed")
    assert.assertHasFunction(methods, "getSailPower")
    assert.assertHasFunction(methods, "getSelfId")
    assert.assertHasFunction(methods, "getSourceId")
    assert.assertHasFunction(methods, "getSpeed")
    assert.assertHasFunction(methods, "getStabilizationStrength")
    assert.assertHasFunction(methods, "getStressContribution")
    assert.assertHasFunction(methods, "getStressImpact")
    assert.assertHasFunction(methods, "getSubnetworkAnchorId")
    assert.assertHasFunction(methods, "getThrust")
    assert.assertHasFunction(methods, "getThrustHandedness")
    assert.assertHasFunction(methods, "getThrustVector")
    assert.assertHasFunction(methods, "getTiltAngle")
    assert.assertHasFunction(methods, "hasSource")
    assert.assertHasFunction(methods, "isActive")
    assert.assertHasFunction(methods, "isAssembled")
    assert.assertHasFunction(methods, "isOverstressed")
    assert.assertHasFunction(methods, "isWoodenTop")
    assert.assertHasFunction(methods, "setManualTarget")
    assert.assertHasFunction(methods, "setThrustHandedness")
end)
suite:test("gyroscopic_propeller_bearing methods are callable", function()
    local methods = mod.types["gyroscopic_propeller_bearing"]
    assert.assertCalls(methods["assemble"])
    assert.assertCalls(methods["clearManualTarget"])
    assert.assertCalls(methods["disassemble"])
    assert.assertCalls(methods["getAirflow"])
    assert.assertCalls(methods["getAngle"])
    assert.assertCalls(methods["getAngularSpeed"])
    assert.assertCalls(methods["getAxis"])
    assert.assertCalls(methods["getBlockNormal"])
    assert.assertCalls(methods["getFacingVector"])
    assert.assertCalls(methods["getKind"])
    assert.assertCalls(methods["getManualTarget"])
    assert.assertCalls(methods["getNetworkId"])
    assert.assertCalls(methods["getRotationSpeed"])
    assert.assertCalls(methods["getSailPower"])
    assert.assertCalls(methods["getSelfId"])
    assert.assertCalls(methods["getSourceId"])
    assert.assertCalls(methods["getSpeed"])
    assert.assertCalls(methods["getStabilizationStrength"])
    assert.assertCalls(methods["getStressContribution"])
    assert.assertCalls(methods["getStressImpact"])
    assert.assertCalls(methods["getSubnetworkAnchorId"])
    assert.assertCalls(methods["getThrust"])
    assert.assertCalls(methods["getThrustHandedness"])
    assert.assertCalls(methods["getThrustVector"])
    assert.assertCalls(methods["getTiltAngle"])
    assert.assertCalls(methods["hasSource"])
    assert.assertCalls(methods["isActive"])
    assert.assertCalls(methods["isAssembled"])
    assert.assertCalls(methods["isOverstressed"])
    assert.assertCalls(methods["isWoodenTop"])
    assert.assertCalls(methods["setManualTarget"])
    assert.assertCalls(methods["setThrustHandedness"])
end)
suite:test("gyroscopic_propeller_bearing stub return types", function()
    local methods = mod.types["gyroscopic_propeller_bearing"]
    assert.assertType(methods["getAirflow"](), "number")
    assert.assertType(methods["getAngle"](), "number")
    assert.assertType(methods["getAngularSpeed"](), "number")
    assert.assertType(methods["getAxis"](), "string")
    assert.assertType(methods["getBlockNormal"](), "table")
    assert.assertType(methods["getFacingVector"](), "table")
    assert.assertType(methods["getKind"](), "string")
    assert.assertType(methods["getManualTarget"](), "table")
    assert.assertType(methods["getNetworkId"](), "string")
    assert.assertType(methods["getRotationSpeed"](), "number")
    assert.assertType(methods["getSailPower"](), "number")
    assert.assertType(methods["getSelfId"](), "string")
    assert.assertType(methods["getSourceId"](), "string")
    assert.assertType(methods["getSpeed"](), "number")
    assert.assertType(methods["getStabilizationStrength"](), "number")
    assert.assertType(methods["getStressContribution"](), "number")
    assert.assertType(methods["getStressImpact"](), "number")
    assert.assertType(methods["getSubnetworkAnchorId"](), "string")
    assert.assertType(methods["getThrust"](), "number")
    assert.assertType(methods["getThrustHandedness"](), "string")
    assert.assertType(methods["getThrustVector"](), "table")
    assert.assertType(methods["getTiltAngle"](), "number")
    assert.assertType(methods["hasSource"](), "boolean")
    assert.assertType(methods["isActive"](), "boolean")
    assert.assertType(methods["isAssembled"](), "boolean")
    assert.assertType(methods["isOverstressed"](), "boolean")
    assert.assertType(methods["isWoodenTop"](), "boolean")
end)
suite:test("type kinetic_provider exists", function()
    assert.assertType(mod.types["kinetic_provider"], "table")
end)
suite:test("kinetic_provider exposes 10 methods", function()
    local methods = mod.types["kinetic_provider"]
    assert.assertHasFunction(methods, "getKind")
    assert.assertHasFunction(methods, "getNetworkId")
    assert.assertHasFunction(methods, "getSelfId")
    assert.assertHasFunction(methods, "getSourceId")
    assert.assertHasFunction(methods, "getSpeed")
    assert.assertHasFunction(methods, "getStressContribution")
    assert.assertHasFunction(methods, "getStressImpact")
    assert.assertHasFunction(methods, "getSubnetworkAnchorId")
    assert.assertHasFunction(methods, "hasSource")
    assert.assertHasFunction(methods, "isOverstressed")
end)
suite:test("kinetic_provider methods are callable", function()
    local methods = mod.types["kinetic_provider"]
    assert.assertCalls(methods["getKind"])
    assert.assertCalls(methods["getNetworkId"])
    assert.assertCalls(methods["getSelfId"])
    assert.assertCalls(methods["getSourceId"])
    assert.assertCalls(methods["getSpeed"])
    assert.assertCalls(methods["getStressContribution"])
    assert.assertCalls(methods["getStressImpact"])
    assert.assertCalls(methods["getSubnetworkAnchorId"])
    assert.assertCalls(methods["hasSource"])
    assert.assertCalls(methods["isOverstressed"])
end)
suite:test("kinetic_provider stub return types", function()
    local methods = mod.types["kinetic_provider"]
    assert.assertType(methods["getKind"](), "string")
    assert.assertType(methods["getNetworkId"](), "string")
    assert.assertType(methods["getSelfId"](), "string")
    assert.assertType(methods["getSourceId"](), "string")
    assert.assertType(methods["getSpeed"](), "number")
    assert.assertType(methods["getStressContribution"](), "number")
    assert.assertType(methods["getStressImpact"](), "number")
    assert.assertType(methods["getSubnetworkAnchorId"](), "string")
    assert.assertType(methods["hasSource"](), "boolean")
    assert.assertType(methods["isOverstressed"](), "boolean")
end)
suite:test("type laser_pointer exists", function()
    assert.assertType(mod.types["laser_pointer"], "table")
end)
suite:test("laser_pointer exposes 8 methods", function()
    local methods = mod.types["laser_pointer"]
    assert.assertHasFunction(methods, "getAxis")
    assert.assertHasFunction(methods, "getColor")
    assert.assertHasFunction(methods, "getPower")
    assert.assertHasFunction(methods, "getRange")
    assert.assertHasFunction(methods, "isFiring")
    assert.assertHasFunction(methods, "isRainbow")
    assert.assertHasFunction(methods, "setColor")
    assert.assertHasFunction(methods, "setRainbow")
end)
suite:test("laser_pointer methods are callable", function()
    local methods = mod.types["laser_pointer"]
    assert.assertCalls(methods["getAxis"])
    assert.assertCalls(methods["getColor"])
    assert.assertCalls(methods["getPower"])
    assert.assertCalls(methods["getRange"])
    assert.assertCalls(methods["isFiring"])
    assert.assertCalls(methods["isRainbow"])
    assert.assertCalls(methods["setColor"])
    assert.assertCalls(methods["setRainbow"])
end)
suite:test("laser_pointer stub return types", function()
    local methods = mod.types["laser_pointer"]
    assert.assertType(methods["getAxis"](), "string")
    assert.assertType(methods["getColor"](), "number")
    assert.assertType(methods["getPower"](), "number")
    assert.assertType(methods["getRange"](), "number")
    assert.assertType(methods["isFiring"](), "boolean")
    assert.assertType(methods["isRainbow"](), "boolean")
end)
suite:test("type laser_sensor exists", function()
    assert.assertType(mod.types["laser_sensor"], "table")
end)
suite:test("laser_sensor exposes 2 methods", function()
    local methods = mod.types["laser_sensor"]
    assert.assertHasFunction(methods, "getClosestHitDistance")
    assert.assertHasFunction(methods, "getPower")
end)
suite:test("laser_sensor methods are callable", function()
    local methods = mod.types["laser_sensor"]
    assert.assertCalls(methods["getClosestHitDistance"])
    assert.assertCalls(methods["getPower"])
end)
suite:test("laser_sensor stub return types", function()
    local methods = mod.types["laser_sensor"]
    assert.assertType(methods["getClosestHitDistance"](), "number")
    assert.assertType(methods["getPower"](), "number")
end)
suite:test("type linked_typewriter exists", function()
    assert.assertType(mod.types["linked_typewriter"], "table")
end)
suite:test("linked_typewriter exposes 0 methods", function()
    local methods = mod.types["linked_typewriter"]
end)
suite:test("linked_typewriter methods are callable", function()
    local methods = mod.types["linked_typewriter"]
end)
suite:test("type mounted_potato_cannon exists", function()
    assert.assertType(mod.types["mounted_potato_cannon"], "table")
end)
suite:test("mounted_potato_cannon exposes 18 methods", function()
    local methods = mod.types["mounted_potato_cannon"]
    assert.assertHasFunction(methods, "getAimingVector")
    assert.assertHasFunction(methods, "getAmmoCount")
    assert.assertHasFunction(methods, "getAmmoType")
    assert.assertHasFunction(methods, "getBarrelPos")
    assert.assertHasFunction(methods, "getBlockedLength")
    assert.assertHasFunction(methods, "getCogwheelSpeed")
    assert.assertHasFunction(methods, "getKind")
    assert.assertHasFunction(methods, "getNetworkId")
    assert.assertHasFunction(methods, "getSelfId")
    assert.assertHasFunction(methods, "getSourceId")
    assert.assertHasFunction(methods, "getSpeed")
    assert.assertHasFunction(methods, "getStressContribution")
    assert.assertHasFunction(methods, "getStressImpact")
    assert.assertHasFunction(methods, "getSubnetworkAnchorId")
    assert.assertHasFunction(methods, "hasAmmo")
    assert.assertHasFunction(methods, "hasSource")
    assert.assertHasFunction(methods, "isBlocked")
    assert.assertHasFunction(methods, "isOverstressed")
end)
suite:test("mounted_potato_cannon methods are callable", function()
    local methods = mod.types["mounted_potato_cannon"]
    assert.assertCalls(methods["getAimingVector"])
    assert.assertCalls(methods["getAmmoCount"])
    assert.assertCalls(methods["getAmmoType"])
    assert.assertCalls(methods["getBarrelPos"])
    assert.assertCalls(methods["getBlockedLength"])
    assert.assertCalls(methods["getCogwheelSpeed"])
    assert.assertCalls(methods["getKind"])
    assert.assertCalls(methods["getNetworkId"])
    assert.assertCalls(methods["getSelfId"])
    assert.assertCalls(methods["getSourceId"])
    assert.assertCalls(methods["getSpeed"])
    assert.assertCalls(methods["getStressContribution"])
    assert.assertCalls(methods["getStressImpact"])
    assert.assertCalls(methods["getSubnetworkAnchorId"])
    assert.assertCalls(methods["hasAmmo"])
    assert.assertCalls(methods["hasSource"])
    assert.assertCalls(methods["isBlocked"])
    assert.assertCalls(methods["isOverstressed"])
end)
suite:test("mounted_potato_cannon stub return types", function()
    local methods = mod.types["mounted_potato_cannon"]
    assert.assertType(methods["getAimingVector"](), "table")
    assert.assertType(methods["getAmmoCount"](), "number")
    assert.assertType(methods["getAmmoType"](), "string")
    assert.assertType(methods["getBarrelPos"](), "table")
    assert.assertType(methods["getBlockedLength"](), "number")
    assert.assertType(methods["getCogwheelSpeed"](), "number")
    assert.assertType(methods["getKind"](), "string")
    assert.assertType(methods["getNetworkId"](), "string")
    assert.assertType(methods["getSelfId"](), "string")
    assert.assertType(methods["getSourceId"](), "string")
    assert.assertType(methods["getSpeed"](), "number")
    assert.assertType(methods["getStressContribution"](), "number")
    assert.assertType(methods["getStressImpact"](), "number")
    assert.assertType(methods["getSubnetworkAnchorId"](), "string")
    assert.assertType(methods["hasAmmo"](), "boolean")
    assert.assertType(methods["hasSource"](), "boolean")
    assert.assertType(methods["isBlocked"](), "boolean")
    assert.assertType(methods["isOverstressed"](), "boolean")
end)
suite:test("type navigation_table exists", function()
    assert.assertType(mod.types["navigation_table"], "table")
end)
suite:test("navigation_table exposes 12 methods", function()
    local methods = mod.types["navigation_table"]
    assert.assertHasFunction(methods, "getBearing")
    assert.assertHasFunction(methods, "getBearingRad")
    assert.assertHasFunction(methods, "getClosureRate")
    assert.assertHasFunction(methods, "getDistanceToTarget")
    assert.assertHasFunction(methods, "getHeading")
    assert.assertHasFunction(methods, "getHeadingRad")
    assert.assertHasFunction(methods, "getOrientation")
    assert.assertHasFunction(methods, "getRelativeAngle")
    assert.assertHasFunction(methods, "getRelativeAngleRad")
    assert.assertHasFunction(methods, "getTargetType")
    assert.assertHasFunction(methods, "getVerticalOffsetToTarget")
    assert.assertHasFunction(methods, "hasTarget")
end)
suite:test("navigation_table methods are callable", function()
    local methods = mod.types["navigation_table"]
    assert.assertCalls(methods["getBearing"])
    assert.assertCalls(methods["getBearingRad"])
    assert.assertCalls(methods["getClosureRate"])
    assert.assertCalls(methods["getDistanceToTarget"])
    assert.assertCalls(methods["getHeading"])
    assert.assertCalls(methods["getHeadingRad"])
    assert.assertCalls(methods["getOrientation"])
    assert.assertCalls(methods["getRelativeAngle"])
    assert.assertCalls(methods["getRelativeAngleRad"])
    assert.assertCalls(methods["getTargetType"])
    assert.assertCalls(methods["getVerticalOffsetToTarget"])
    assert.assertCalls(methods["hasTarget"])
end)
suite:test("navigation_table stub return types", function()
    local methods = mod.types["navigation_table"]
    assert.assertType(methods["getBearing"](), "number")
    assert.assertType(methods["getBearingRad"](), "number")
    assert.assertType(methods["getClosureRate"](), "number")
    assert.assertType(methods["getDistanceToTarget"](), "number")
    assert.assertType(methods["getHeading"](), "number")
    assert.assertType(methods["getHeadingRad"](), "number")
    assert.assertType(methods["getOrientation"](), "table")
    assert.assertType(methods["getRelativeAngle"](), "number")
    assert.assertType(methods["getRelativeAngleRad"](), "number")
    assert.assertType(methods["getTargetType"](), "string")
    assert.assertType(methods["getVerticalOffsetToTarget"](), "number")
    assert.assertType(methods["hasTarget"](), "boolean")
end)
suite:test("type physics_assembler exists", function()
    assert.assertType(mod.types["physics_assembler"], "table")
end)
suite:test("physics_assembler exposes 6 methods", function()
    local methods = mod.types["physics_assembler"]
    assert.assertHasFunction(methods, "getCenterOfMass")
    assert.assertHasFunction(methods, "getInertiaTensor")
    assert.assertHasFunction(methods, "getMass")
    assert.assertHasFunction(methods, "getSubLevelId")
    assert.assertHasFunction(methods, "getSubLevelName")
    assert.assertHasFunction(methods, "isAssembled")
end)
suite:test("physics_assembler methods are callable", function()
    local methods = mod.types["physics_assembler"]
    assert.assertCalls(methods["getCenterOfMass"])
    assert.assertCalls(methods["getInertiaTensor"])
    assert.assertCalls(methods["getMass"])
    assert.assertCalls(methods["getSubLevelId"])
    assert.assertCalls(methods["getSubLevelName"])
    assert.assertCalls(methods["isAssembled"])
end)
suite:test("physics_assembler stub return types", function()
    local methods = mod.types["physics_assembler"]
    assert.assertType(methods["getCenterOfMass"](), "table")
    assert.assertType(methods["getInertiaTensor"](), "table")
    assert.assertType(methods["getMass"](), "number")
    assert.assertType(methods["getSubLevelId"](), "string")
    assert.assertType(methods["getSubLevelName"](), "string")
    assert.assertType(methods["isAssembled"](), "boolean")
end)
suite:test("type portable_engine exists", function()
    assert.assertType(mod.types["portable_engine"], "table")
end)
suite:test("portable_engine exposes 17 methods", function()
    local methods = mod.types["portable_engine"]
    assert.assertHasFunction(methods, "getBurnTime")
    assert.assertHasFunction(methods, "getGeneratedSpeed")
    assert.assertHasFunction(methods, "getKind")
    assert.assertHasFunction(methods, "getNetworkId")
    assert.assertHasFunction(methods, "getSelfId")
    assert.assertHasFunction(methods, "getSourceId")
    assert.assertHasFunction(methods, "getSpeed")
    assert.assertHasFunction(methods, "getStressContribution")
    assert.assertHasFunction(methods, "getStressImpact")
    assert.assertHasFunction(methods, "getSubnetworkAnchorId")
    assert.assertHasFunction(methods, "getTotalBurnTime")
    assert.assertHasFunction(methods, "hasSource")
    assert.assertHasFunction(methods, "isCurrentFuelInfinite")
    assert.assertHasFunction(methods, "isLit")
    assert.assertHasFunction(methods, "isOverstressed")
    assert.assertHasFunction(methods, "isSuperHeated")
    assert.assertHasFunction(methods, "isTotalFuelInfinite")
end)
suite:test("portable_engine methods are callable", function()
    local methods = mod.types["portable_engine"]
    assert.assertCalls(methods["getBurnTime"])
    assert.assertCalls(methods["getGeneratedSpeed"])
    assert.assertCalls(methods["getKind"])
    assert.assertCalls(methods["getNetworkId"])
    assert.assertCalls(methods["getSelfId"])
    assert.assertCalls(methods["getSourceId"])
    assert.assertCalls(methods["getSpeed"])
    assert.assertCalls(methods["getStressContribution"])
    assert.assertCalls(methods["getStressImpact"])
    assert.assertCalls(methods["getSubnetworkAnchorId"])
    assert.assertCalls(methods["getTotalBurnTime"])
    assert.assertCalls(methods["hasSource"])
    assert.assertCalls(methods["isCurrentFuelInfinite"])
    assert.assertCalls(methods["isLit"])
    assert.assertCalls(methods["isOverstressed"])
    assert.assertCalls(methods["isSuperHeated"])
    assert.assertCalls(methods["isTotalFuelInfinite"])
end)
suite:test("portable_engine stub return types", function()
    local methods = mod.types["portable_engine"]
    assert.assertType(methods["getBurnTime"](), "number")
    assert.assertType(methods["getGeneratedSpeed"](), "number")
    assert.assertType(methods["getKind"](), "string")
    assert.assertType(methods["getNetworkId"](), "string")
    assert.assertType(methods["getSelfId"](), "string")
    assert.assertType(methods["getSourceId"](), "string")
    assert.assertType(methods["getSpeed"](), "number")
    assert.assertType(methods["getStressContribution"](), "number")
    assert.assertType(methods["getStressImpact"](), "number")
    assert.assertType(methods["getSubnetworkAnchorId"](), "string")
    assert.assertType(methods["getTotalBurnTime"](), "number")
    assert.assertType(methods["hasSource"](), "boolean")
    assert.assertType(methods["isCurrentFuelInfinite"](), "boolean")
    assert.assertType(methods["isLit"](), "boolean")
    assert.assertType(methods["isOverstressed"](), "boolean")
    assert.assertType(methods["isSuperHeated"](), "boolean")
    assert.assertType(methods["isTotalFuelInfinite"](), "boolean")
end)
suite:test("type propeller exists", function()
    assert.assertType(mod.types["propeller"], "table")
end)
suite:test("propeller exposes 15 methods", function()
    local methods = mod.types["propeller"]
    assert.assertHasFunction(methods, "getAirflow")
    assert.assertHasFunction(methods, "getAxis")
    assert.assertHasFunction(methods, "getKind")
    assert.assertHasFunction(methods, "getNetworkId")
    assert.assertHasFunction(methods, "getRotationSpeed")
    assert.assertHasFunction(methods, "getSelfId")
    assert.assertHasFunction(methods, "getSourceId")
    assert.assertHasFunction(methods, "getSpeed")
    assert.assertHasFunction(methods, "getStressContribution")
    assert.assertHasFunction(methods, "getStressImpact")
    assert.assertHasFunction(methods, "getSubnetworkAnchorId")
    assert.assertHasFunction(methods, "getThrust")
    assert.assertHasFunction(methods, "hasSource")
    assert.assertHasFunction(methods, "isActive")
    assert.assertHasFunction(methods, "isOverstressed")
end)
suite:test("propeller methods are callable", function()
    local methods = mod.types["propeller"]
    assert.assertCalls(methods["getAirflow"])
    assert.assertCalls(methods["getAxis"])
    assert.assertCalls(methods["getKind"])
    assert.assertCalls(methods["getNetworkId"])
    assert.assertCalls(methods["getRotationSpeed"])
    assert.assertCalls(methods["getSelfId"])
    assert.assertCalls(methods["getSourceId"])
    assert.assertCalls(methods["getSpeed"])
    assert.assertCalls(methods["getStressContribution"])
    assert.assertCalls(methods["getStressImpact"])
    assert.assertCalls(methods["getSubnetworkAnchorId"])
    assert.assertCalls(methods["getThrust"])
    assert.assertCalls(methods["hasSource"])
    assert.assertCalls(methods["isActive"])
    assert.assertCalls(methods["isOverstressed"])
end)
suite:test("propeller stub return types", function()
    local methods = mod.types["propeller"]
    assert.assertType(methods["getAirflow"](), "number")
    assert.assertType(methods["getAxis"](), "string")
    assert.assertType(methods["getKind"](), "string")
    assert.assertType(methods["getNetworkId"](), "string")
    assert.assertType(methods["getRotationSpeed"](), "number")
    assert.assertType(methods["getSelfId"](), "string")
    assert.assertType(methods["getSourceId"](), "string")
    assert.assertType(methods["getSpeed"](), "number")
    assert.assertType(methods["getStressContribution"](), "number")
    assert.assertType(methods["getStressImpact"](), "number")
    assert.assertType(methods["getSubnetworkAnchorId"](), "string")
    assert.assertType(methods["getThrust"](), "number")
    assert.assertType(methods["hasSource"](), "boolean")
    assert.assertType(methods["isActive"](), "boolean")
    assert.assertType(methods["isOverstressed"](), "boolean")
end)
suite:test("type propeller_bearing exists", function()
    assert.assertType(mod.types["propeller_bearing"], "table")
end)
suite:test("propeller_bearing exposes 26 methods", function()
    local methods = mod.types["propeller_bearing"]
    assert.assertHasFunction(methods, "assemble")
    assert.assertHasFunction(methods, "disassemble")
    assert.assertHasFunction(methods, "getAirflow")
    assert.assertHasFunction(methods, "getAngle")
    assert.assertHasFunction(methods, "getAngularSpeed")
    assert.assertHasFunction(methods, "getAxis")
    assert.assertHasFunction(methods, "getFacingVector")
    assert.assertHasFunction(methods, "getKind")
    assert.assertHasFunction(methods, "getNetworkId")
    assert.assertHasFunction(methods, "getRotationSpeed")
    assert.assertHasFunction(methods, "getSailPower")
    assert.assertHasFunction(methods, "getSelfId")
    assert.assertHasFunction(methods, "getSourceId")
    assert.assertHasFunction(methods, "getSpeed")
    assert.assertHasFunction(methods, "getStressContribution")
    assert.assertHasFunction(methods, "getStressImpact")
    assert.assertHasFunction(methods, "getSubnetworkAnchorId")
    assert.assertHasFunction(methods, "getThrust")
    assert.assertHasFunction(methods, "getThrustHandedness")
    assert.assertHasFunction(methods, "getThrustVector")
    assert.assertHasFunction(methods, "hasSource")
    assert.assertHasFunction(methods, "isActive")
    assert.assertHasFunction(methods, "isAssembled")
    assert.assertHasFunction(methods, "isOverstressed")
    assert.assertHasFunction(methods, "isWoodenTop")
    assert.assertHasFunction(methods, "setThrustHandedness")
end)
suite:test("propeller_bearing methods are callable", function()
    local methods = mod.types["propeller_bearing"]
    assert.assertCalls(methods["assemble"])
    assert.assertCalls(methods["disassemble"])
    assert.assertCalls(methods["getAirflow"])
    assert.assertCalls(methods["getAngle"])
    assert.assertCalls(methods["getAngularSpeed"])
    assert.assertCalls(methods["getAxis"])
    assert.assertCalls(methods["getFacingVector"])
    assert.assertCalls(methods["getKind"])
    assert.assertCalls(methods["getNetworkId"])
    assert.assertCalls(methods["getRotationSpeed"])
    assert.assertCalls(methods["getSailPower"])
    assert.assertCalls(methods["getSelfId"])
    assert.assertCalls(methods["getSourceId"])
    assert.assertCalls(methods["getSpeed"])
    assert.assertCalls(methods["getStressContribution"])
    assert.assertCalls(methods["getStressImpact"])
    assert.assertCalls(methods["getSubnetworkAnchorId"])
    assert.assertCalls(methods["getThrust"])
    assert.assertCalls(methods["getThrustHandedness"])
    assert.assertCalls(methods["getThrustVector"])
    assert.assertCalls(methods["hasSource"])
    assert.assertCalls(methods["isActive"])
    assert.assertCalls(methods["isAssembled"])
    assert.assertCalls(methods["isOverstressed"])
    assert.assertCalls(methods["isWoodenTop"])
    assert.assertCalls(methods["setThrustHandedness"])
end)
suite:test("propeller_bearing stub return types", function()
    local methods = mod.types["propeller_bearing"]
    assert.assertType(methods["getAirflow"](), "number")
    assert.assertType(methods["getAngle"](), "number")
    assert.assertType(methods["getAngularSpeed"](), "number")
    assert.assertType(methods["getAxis"](), "string")
    assert.assertType(methods["getFacingVector"](), "table")
    assert.assertType(methods["getKind"](), "string")
    assert.assertType(methods["getNetworkId"](), "string")
    assert.assertType(methods["getRotationSpeed"](), "number")
    assert.assertType(methods["getSailPower"](), "number")
    assert.assertType(methods["getSelfId"](), "string")
    assert.assertType(methods["getSourceId"](), "string")
    assert.assertType(methods["getSpeed"](), "number")
    assert.assertType(methods["getStressContribution"](), "number")
    assert.assertType(methods["getStressImpact"](), "number")
    assert.assertType(methods["getSubnetworkAnchorId"](), "string")
    assert.assertType(methods["getThrust"](), "number")
    assert.assertType(methods["getThrustHandedness"](), "string")
    assert.assertType(methods["getThrustVector"](), "table")
    assert.assertType(methods["hasSource"](), "boolean")
    assert.assertType(methods["isActive"](), "boolean")
    assert.assertType(methods["isAssembled"](), "boolean")
    assert.assertType(methods["isOverstressed"](), "boolean")
    assert.assertType(methods["isWoodenTop"](), "boolean")
end)
suite:test("type rope_winch exists", function()
    assert.assertType(mod.types["rope_winch"], "table")
end)
suite:test("rope_winch exposes 14 methods", function()
    local methods = mod.types["rope_winch"]
    assert.assertHasFunction(methods, "getKind")
    assert.assertHasFunction(methods, "getLength")
    assert.assertHasFunction(methods, "getMaxLength")
    assert.assertHasFunction(methods, "getMinLength")
    assert.assertHasFunction(methods, "getMovementSpeed")
    assert.assertHasFunction(methods, "getNetworkId")
    assert.assertHasFunction(methods, "getSelfId")
    assert.assertHasFunction(methods, "getSourceId")
    assert.assertHasFunction(methods, "getSpeed")
    assert.assertHasFunction(methods, "getStressContribution")
    assert.assertHasFunction(methods, "getStressImpact")
    assert.assertHasFunction(methods, "getSubnetworkAnchorId")
    assert.assertHasFunction(methods, "hasSource")
    assert.assertHasFunction(methods, "isOverstressed")
end)
suite:test("rope_winch methods are callable", function()
    local methods = mod.types["rope_winch"]
    assert.assertCalls(methods["getKind"])
    assert.assertCalls(methods["getLength"])
    assert.assertCalls(methods["getMaxLength"])
    assert.assertCalls(methods["getMinLength"])
    assert.assertCalls(methods["getMovementSpeed"])
    assert.assertCalls(methods["getNetworkId"])
    assert.assertCalls(methods["getSelfId"])
    assert.assertCalls(methods["getSourceId"])
    assert.assertCalls(methods["getSpeed"])
    assert.assertCalls(methods["getStressContribution"])
    assert.assertCalls(methods["getStressImpact"])
    assert.assertCalls(methods["getSubnetworkAnchorId"])
    assert.assertCalls(methods["hasSource"])
    assert.assertCalls(methods["isOverstressed"])
end)
suite:test("rope_winch stub return types", function()
    local methods = mod.types["rope_winch"]
    assert.assertType(methods["getKind"](), "string")
    assert.assertType(methods["getLength"](), "number")
    assert.assertType(methods["getMaxLength"](), "number")
    assert.assertType(methods["getMinLength"](), "number")
    assert.assertType(methods["getMovementSpeed"](), "number")
    assert.assertType(methods["getNetworkId"](), "string")
    assert.assertType(methods["getSelfId"](), "string")
    assert.assertType(methods["getSourceId"](), "string")
    assert.assertType(methods["getSpeed"](), "number")
    assert.assertType(methods["getStressContribution"](), "number")
    assert.assertType(methods["getStressImpact"](), "number")
    assert.assertType(methods["getSubnetworkAnchorId"](), "string")
    assert.assertType(methods["hasSource"](), "boolean")
    assert.assertType(methods["isOverstressed"](), "boolean")
end)
suite:test("type steering_wheel exists", function()
    assert.assertType(mod.types["steering_wheel"], "table")
end)
suite:test("steering_wheel exposes 17 methods", function()
    local methods = mod.types["steering_wheel"]
    assert.assertHasFunction(methods, "getAngle")
    assert.assertHasFunction(methods, "getAngleRad")
    assert.assertHasFunction(methods, "getKind")
    assert.assertHasFunction(methods, "getMaxAngle")
    assert.assertHasFunction(methods, "getNetworkId")
    assert.assertHasFunction(methods, "getNormalizedAngle")
    assert.assertHasFunction(methods, "getSelfId")
    assert.assertHasFunction(methods, "getSourceId")
    assert.assertHasFunction(methods, "getSpeed")
    assert.assertHasFunction(methods, "getStressContribution")
    assert.assertHasFunction(methods, "getStressImpact")
    assert.assertHasFunction(methods, "getSubnetworkAnchorId")
    assert.assertHasFunction(methods, "getTargetAngle")
    assert.assertHasFunction(methods, "getTargetAngleRad")
    assert.assertHasFunction(methods, "hasSource")
    assert.assertHasFunction(methods, "isHeld")
    assert.assertHasFunction(methods, "isOverstressed")
end)
suite:test("steering_wheel methods are callable", function()
    local methods = mod.types["steering_wheel"]
    assert.assertCalls(methods["getAngle"])
    assert.assertCalls(methods["getAngleRad"])
    assert.assertCalls(methods["getKind"])
    assert.assertCalls(methods["getMaxAngle"])
    assert.assertCalls(methods["getNetworkId"])
    assert.assertCalls(methods["getNormalizedAngle"])
    assert.assertCalls(methods["getSelfId"])
    assert.assertCalls(methods["getSourceId"])
    assert.assertCalls(methods["getSpeed"])
    assert.assertCalls(methods["getStressContribution"])
    assert.assertCalls(methods["getStressImpact"])
    assert.assertCalls(methods["getSubnetworkAnchorId"])
    assert.assertCalls(methods["getTargetAngle"])
    assert.assertCalls(methods["getTargetAngleRad"])
    assert.assertCalls(methods["hasSource"])
    assert.assertCalls(methods["isHeld"])
    assert.assertCalls(methods["isOverstressed"])
end)
suite:test("steering_wheel stub return types", function()
    local methods = mod.types["steering_wheel"]
    assert.assertType(methods["getAngle"](), "number")
    assert.assertType(methods["getAngleRad"](), "number")
    assert.assertType(methods["getKind"](), "string")
    assert.assertType(methods["getMaxAngle"](), "number")
    assert.assertType(methods["getNetworkId"](), "string")
    assert.assertType(methods["getNormalizedAngle"](), "number")
    assert.assertType(methods["getSelfId"](), "string")
    assert.assertType(methods["getSourceId"](), "string")
    assert.assertType(methods["getSpeed"](), "number")
    assert.assertType(methods["getStressContribution"](), "number")
    assert.assertType(methods["getStressImpact"](), "number")
    assert.assertType(methods["getSubnetworkAnchorId"](), "string")
    assert.assertType(methods["getTargetAngle"](), "number")
    assert.assertType(methods["getTargetAngleRad"](), "number")
    assert.assertType(methods["hasSource"](), "boolean")
    assert.assertType(methods["isHeld"](), "boolean")
    assert.assertType(methods["isOverstressed"](), "boolean")
end)
suite:test("type swivel_bearing exists", function()
    assert.assertType(mod.types["swivel_bearing"], "table")
end)
suite:test("swivel_bearing exposes 21 methods", function()
    local methods = mod.types["swivel_bearing"]
    assert.assertHasFunction(methods, "assemble")
    assert.assertHasFunction(methods, "disassemble")
    assert.assertHasFunction(methods, "getKind")
    assert.assertHasFunction(methods, "getLastAssemblyException")
    assert.assertHasFunction(methods, "getLockingMode")
    assert.assertHasFunction(methods, "getNetworkId")
    assert.assertHasFunction(methods, "getPlateId")
    assert.assertHasFunction(methods, "getSelfId")
    assert.assertHasFunction(methods, "getSourceId")
    assert.assertHasFunction(methods, "getSpeed")
    assert.assertHasFunction(methods, "getStressContribution")
    assert.assertHasFunction(methods, "getStressImpact")
    assert.assertHasFunction(methods, "getSubLevelId")
    assert.assertHasFunction(methods, "getSubnetworkAnchorId")
    assert.assertHasFunction(methods, "getTargetAngle")
    assert.assertHasFunction(methods, "getTargetAngleRad")
    assert.assertHasFunction(methods, "hasSource")
    assert.assertHasFunction(methods, "isAssembled")
    assert.assertHasFunction(methods, "isLocked")
    assert.assertHasFunction(methods, "isOverstressed")
    assert.assertHasFunction(methods, "setLockingMode")
end)
suite:test("swivel_bearing methods are callable", function()
    local methods = mod.types["swivel_bearing"]
    assert.assertCalls(methods["assemble"])
    assert.assertCalls(methods["disassemble"])
    assert.assertCalls(methods["getKind"])
    assert.assertCalls(methods["getLastAssemblyException"])
    assert.assertCalls(methods["getLockingMode"])
    assert.assertCalls(methods["getNetworkId"])
    assert.assertCalls(methods["getPlateId"])
    assert.assertCalls(methods["getSelfId"])
    assert.assertCalls(methods["getSourceId"])
    assert.assertCalls(methods["getSpeed"])
    assert.assertCalls(methods["getStressContribution"])
    assert.assertCalls(methods["getStressImpact"])
    assert.assertCalls(methods["getSubLevelId"])
    assert.assertCalls(methods["getSubnetworkAnchorId"])
    assert.assertCalls(methods["getTargetAngle"])
    assert.assertCalls(methods["getTargetAngleRad"])
    assert.assertCalls(methods["hasSource"])
    assert.assertCalls(methods["isAssembled"])
    assert.assertCalls(methods["isLocked"])
    assert.assertCalls(methods["isOverstressed"])
    assert.assertCalls(methods["setLockingMode"])
end)
suite:test("swivel_bearing stub return types", function()
    local methods = mod.types["swivel_bearing"]
    assert.assertType(methods["getKind"](), "string")
    assert.assertType(methods["getLastAssemblyException"](), "string")
    assert.assertType(methods["getLockingMode"](), "string")
    assert.assertType(methods["getNetworkId"](), "string")
    assert.assertType(methods["getPlateId"](), "string")
    assert.assertType(methods["getSelfId"](), "string")
    assert.assertType(methods["getSourceId"](), "string")
    assert.assertType(methods["getSpeed"](), "number")
    assert.assertType(methods["getStressContribution"](), "number")
    assert.assertType(methods["getStressImpact"](), "number")
    assert.assertType(methods["getSubLevelId"](), "string")
    assert.assertType(methods["getSubnetworkAnchorId"](), "string")
    assert.assertType(methods["getTargetAngle"](), "number")
    assert.assertType(methods["getTargetAngleRad"](), "number")
    assert.assertType(methods["hasSource"](), "boolean")
    assert.assertType(methods["isAssembled"](), "boolean")
    assert.assertType(methods["isLocked"](), "boolean")
    assert.assertType(methods["isOverstressed"](), "boolean")
end)
suite:test("type throttle_lever exists", function()
    assert.assertType(mod.types["throttle_lever"], "table")
end)
suite:test("throttle_lever exposes 2 methods", function()
    local methods = mod.types["throttle_lever"]
    assert.assertHasFunction(methods, "getState")
    assert.assertHasFunction(methods, "setSignal")
end)
suite:test("throttle_lever methods are callable", function()
    local methods = mod.types["throttle_lever"]
    assert.assertCalls(methods["getState"])
    assert.assertCalls(methods["setSignal"])
end)
suite:test("throttle_lever stub return types", function()
    local methods = mod.types["throttle_lever"]
    assert.assertType(methods["getState"](), "number")
end)
suite:test("type torsion_spring exists", function()
    assert.assertType(mod.types["torsion_spring"], "table")
end)
suite:test("torsion_spring exposes 15 methods", function()
    local methods = mod.types["torsion_spring"]
    assert.assertHasFunction(methods, "getAngle")
    assert.assertHasFunction(methods, "getAngleRad")
    assert.assertHasFunction(methods, "getKind")
    assert.assertHasFunction(methods, "getLimit")
    assert.assertHasFunction(methods, "getNetworkId")
    assert.assertHasFunction(methods, "getSelfId")
    assert.assertHasFunction(methods, "getSourceId")
    assert.assertHasFunction(methods, "getSpeed")
    assert.assertHasFunction(methods, "getStressContribution")
    assert.assertHasFunction(methods, "getStressImpact")
    assert.assertHasFunction(methods, "getSubnetworkAnchorId")
    assert.assertHasFunction(methods, "hasSource")
    assert.assertHasFunction(methods, "isOverstressed")
    assert.assertHasFunction(methods, "isRunning")
    assert.assertHasFunction(methods, "setLimit")
end)
suite:test("torsion_spring methods are callable", function()
    local methods = mod.types["torsion_spring"]
    assert.assertCalls(methods["getAngle"])
    assert.assertCalls(methods["getAngleRad"])
    assert.assertCalls(methods["getKind"])
    assert.assertCalls(methods["getLimit"])
    assert.assertCalls(methods["getNetworkId"])
    assert.assertCalls(methods["getSelfId"])
    assert.assertCalls(methods["getSourceId"])
    assert.assertCalls(methods["getSpeed"])
    assert.assertCalls(methods["getStressContribution"])
    assert.assertCalls(methods["getStressImpact"])
    assert.assertCalls(methods["getSubnetworkAnchorId"])
    assert.assertCalls(methods["hasSource"])
    assert.assertCalls(methods["isOverstressed"])
    assert.assertCalls(methods["isRunning"])
    assert.assertCalls(methods["setLimit"])
end)
suite:test("torsion_spring stub return types", function()
    local methods = mod.types["torsion_spring"]
    assert.assertType(methods["getAngle"](), "number")
    assert.assertType(methods["getAngleRad"](), "number")
    assert.assertType(methods["getKind"](), "string")
    assert.assertType(methods["getLimit"](), "number")
    assert.assertType(methods["getNetworkId"](), "string")
    assert.assertType(methods["getSelfId"](), "string")
    assert.assertType(methods["getSourceId"](), "string")
    assert.assertType(methods["getSpeed"](), "number")
    assert.assertType(methods["getStressContribution"](), "number")
    assert.assertType(methods["getStressImpact"](), "number")
    assert.assertType(methods["getSubnetworkAnchorId"](), "string")
    assert.assertType(methods["hasSource"](), "boolean")
    assert.assertType(methods["isOverstressed"](), "boolean")
    assert.assertType(methods["isRunning"](), "boolean")
end)
suite:test("type velocity_sensor exists", function()
    assert.assertType(mod.types["velocity_sensor"], "table")
end)
suite:test("velocity_sensor exposes 2 methods", function()
    local methods = mod.types["velocity_sensor"]
    assert.assertHasFunction(methods, "getAxis")
    assert.assertHasFunction(methods, "getVelocity")
end)
suite:test("velocity_sensor methods are callable", function()
    local methods = mod.types["velocity_sensor"]
    assert.assertCalls(methods["getAxis"])
    assert.assertCalls(methods["getVelocity"])
end)
suite:test("velocity_sensor stub return types", function()
    local methods = mod.types["velocity_sensor"]
    assert.assertType(methods["getAxis"](), "string")
    assert.assertType(methods["getVelocity"](), "number")
end)
suite:test("type wheel_mount exists", function()
    assert.assertType(mod.types["wheel_mount"], "table")
end)
suite:test("wheel_mount exposes 25 methods", function()
    local methods = mod.types["wheel_mount"]
    assert.assertHasFunction(methods, "clearBrake")
    assert.assertHasFunction(methods, "clearSteering")
    assert.assertHasFunction(methods, "getAngularVelocity")
    assert.assertHasFunction(methods, "getBrake")
    assert.assertHasFunction(methods, "getExtension")
    assert.assertHasFunction(methods, "getKind")
    assert.assertHasFunction(methods, "getNetworkId")
    assert.assertHasFunction(methods, "getSelfId")
    assert.assertHasFunction(methods, "getSourceId")
    assert.assertHasFunction(methods, "getSpeed")
    assert.assertHasFunction(methods, "getSteering")
    assert.assertHasFunction(methods, "getSteeringAngle")
    assert.assertHasFunction(methods, "getStressContribution")
    assert.assertHasFunction(methods, "getStressImpact")
    assert.assertHasFunction(methods, "getSubnetworkAnchorId")
    assert.assertHasFunction(methods, "getTireRadius")
    assert.assertHasFunction(methods, "getTouchingFriction")
    assert.assertHasFunction(methods, "hasSource")
    assert.assertHasFunction(methods, "hasTire")
    assert.assertHasFunction(methods, "isBrakeOverridden")
    assert.assertHasFunction(methods, "isLiftedUp")
    assert.assertHasFunction(methods, "isOverstressed")
    assert.assertHasFunction(methods, "isSteeringOverridden")
    assert.assertHasFunction(methods, "setBrake")
    assert.assertHasFunction(methods, "setSteering")
end)
suite:test("wheel_mount methods are callable", function()
    local methods = mod.types["wheel_mount"]
    assert.assertCalls(methods["clearBrake"])
    assert.assertCalls(methods["clearSteering"])
    assert.assertCalls(methods["getAngularVelocity"])
    assert.assertCalls(methods["getBrake"])
    assert.assertCalls(methods["getExtension"])
    assert.assertCalls(methods["getKind"])
    assert.assertCalls(methods["getNetworkId"])
    assert.assertCalls(methods["getSelfId"])
    assert.assertCalls(methods["getSourceId"])
    assert.assertCalls(methods["getSpeed"])
    assert.assertCalls(methods["getSteering"])
    assert.assertCalls(methods["getSteeringAngle"])
    assert.assertCalls(methods["getStressContribution"])
    assert.assertCalls(methods["getStressImpact"])
    assert.assertCalls(methods["getSubnetworkAnchorId"])
    assert.assertCalls(methods["getTireRadius"])
    assert.assertCalls(methods["getTouchingFriction"])
    assert.assertCalls(methods["hasSource"])
    assert.assertCalls(methods["hasTire"])
    assert.assertCalls(methods["isBrakeOverridden"])
    assert.assertCalls(methods["isLiftedUp"])
    assert.assertCalls(methods["isOverstressed"])
    assert.assertCalls(methods["isSteeringOverridden"])
    assert.assertCalls(methods["setBrake"])
    assert.assertCalls(methods["setSteering"])
end)
suite:test("wheel_mount stub return types", function()
    local methods = mod.types["wheel_mount"]
    assert.assertType(methods["getAngularVelocity"](), "number")
    assert.assertType(methods["getBrake"](), "number")
    assert.assertType(methods["getExtension"](), "number")
    assert.assertType(methods["getKind"](), "string")
    assert.assertType(methods["getNetworkId"](), "string")
    assert.assertType(methods["getSelfId"](), "string")
    assert.assertType(methods["getSourceId"](), "string")
    assert.assertType(methods["getSpeed"](), "number")
    assert.assertType(methods["getSteering"](), "number")
    assert.assertType(methods["getSteeringAngle"](), "number")
    assert.assertType(methods["getStressContribution"](), "number")
    assert.assertType(methods["getStressImpact"](), "number")
    assert.assertType(methods["getSubnetworkAnchorId"](), "string")
    assert.assertType(methods["getTireRadius"](), "number")
    assert.assertType(methods["getTouchingFriction"](), "number")
    assert.assertType(methods["hasSource"](), "boolean")
    assert.assertType(methods["hasTire"](), "boolean")
    assert.assertType(methods["isBrakeOverridden"](), "boolean")
    assert.assertType(methods["isLiftedUp"](), "boolean")
    assert.assertType(methods["isOverstressed"](), "boolean")
    assert.assertType(methods["isSteeringOverridden"](), "boolean")
end)

local passed, failed = suite:summary()
return passed, failed
