-- tests/mock_api/test_advancedperipherals.lua
-- GENERATED completeness tests for mock_api/advancedperipherals.lua (from api-docs inventory).
-- Regenerate with gen_tests.py. Every peripheral type must exist, expose its
-- documented methods, and each method must be callable with no arguments.
-- Methods with deterministic stub defaults additionally assert return types.

package.path = package.path .. ";./?.lua"

local assert = require("tests.helpers.assert")
local mod = require("mock_api.advancedperipherals")

local suite = assert.suite("advancedperipherals")

suite:test("type block_reader exists", function()
    assert.assertType(mod.types["block_reader"], "table")
end)
suite:test("block_reader exposes 5 methods", function()
    local methods = mod.types["block_reader"]
    assert.assertHasFunction(methods, "getBlockData")
    assert.assertHasFunction(methods, "getBlockName")
    assert.assertHasFunction(methods, "getBlockStates")
    assert.assertHasFunction(methods, "getName")
    assert.assertHasFunction(methods, "isTileEntity")
end)
suite:test("block_reader methods are callable", function()
    local methods = mod.types["block_reader"]
    assert.assertCalls(methods["getBlockData"])
    assert.assertCalls(methods["getBlockName"])
    assert.assertCalls(methods["getBlockStates"])
    assert.assertCalls(methods["getName"])
    assert.assertCalls(methods["isTileEntity"])
end)
suite:test("block_reader stub return types", function()
    local methods = mod.types["block_reader"]
    assert.assertType(methods["getBlockName"](), "string")
    assert.assertType(methods["getName"](), "string")
    assert.assertType(methods["isTileEntity"](), "boolean")
end)
suite:test("type chat_box exists", function()
    assert.assertType(mod.types["chat_box"], "table")
end)
suite:test("chat_box exposes 7 methods", function()
    local methods = mod.types["chat_box"]
    assert.assertHasFunction(methods, "getName")
    assert.assertHasFunction(methods, "sendFormattedMessage")
    assert.assertHasFunction(methods, "sendFormattedMessageToPlayer")
    assert.assertHasFunction(methods, "sendFormattedToastToPlayer")
    assert.assertHasFunction(methods, "sendMessage")
    assert.assertHasFunction(methods, "sendMessageToPlayer")
    assert.assertHasFunction(methods, "sendToastToPlayer")
end)
suite:test("chat_box methods are callable", function()
    local methods = mod.types["chat_box"]
    assert.assertCalls(methods["getName"])
    assert.assertCalls(methods["sendFormattedMessage"])
    assert.assertCalls(methods["sendFormattedMessageToPlayer"])
    assert.assertCalls(methods["sendFormattedToastToPlayer"])
    assert.assertCalls(methods["sendMessage"])
    assert.assertCalls(methods["sendMessageToPlayer"])
    assert.assertCalls(methods["sendToastToPlayer"])
end)
suite:test("chat_box stub return types", function()
    local methods = mod.types["chat_box"]
    assert.assertType(methods["getName"](), "string")
    assert.assertType(methods["sendFormattedMessage"](), "table")
    assert.assertType(methods["sendFormattedMessageToPlayer"](), "table")
    assert.assertType(methods["sendFormattedToastToPlayer"](), "table")
    assert.assertType(methods["sendMessage"](), "table")
    assert.assertType(methods["sendMessageToPlayer"](), "table")
    assert.assertType(methods["sendToastToPlayer"](), "table")
end)
suite:test("type chunky exists", function()
    assert.assertType(mod.types["chunky"], "table")
end)
suite:test("chunky exposes 1 methods", function()
    local methods = mod.types["chunky"]
    assert.assertHasFunction(methods, "getName")
end)
suite:test("chunky methods are callable", function()
    local methods = mod.types["chunky"]
    assert.assertCalls(methods["getName"])
end)
suite:test("chunky stub return types", function()
    local methods = mod.types["chunky"]
    assert.assertType(methods["getName"](), "string")
end)
suite:test("type colony_integrator exists", function()
    assert.assertType(mod.types["colony_integrator"], "table")
end)
suite:test("colony_integrator exposes 23 methods", function()
    local methods = mod.types["colony_integrator"]
    assert.assertHasFunction(methods, "amountOfCitizens")
    assert.assertHasFunction(methods, "amountOfConstructionSites")
    assert.assertHasFunction(methods, "amountOfGraves")
    assert.assertHasFunction(methods, "getBuilderResources")
    assert.assertHasFunction(methods, "getBuildings")
    assert.assertHasFunction(methods, "getCitizens")
    assert.assertHasFunction(methods, "getColonyID")
    assert.assertHasFunction(methods, "getColonyName")
    assert.assertHasFunction(methods, "getColonyStyle")
    assert.assertHasFunction(methods, "getHappiness")
    assert.assertHasFunction(methods, "getLocation")
    assert.assertHasFunction(methods, "getName")
    assert.assertHasFunction(methods, "getRequests")
    assert.assertHasFunction(methods, "getResearch")
    assert.assertHasFunction(methods, "getVisitors")
    assert.assertHasFunction(methods, "getWorkOrderResources")
    assert.assertHasFunction(methods, "getWorkOrders")
    assert.assertHasFunction(methods, "isActive")
    assert.assertHasFunction(methods, "isInColony")
    assert.assertHasFunction(methods, "isUnderAttack")
    assert.assertHasFunction(methods, "isUnderRaid")
    assert.assertHasFunction(methods, "isWithin")
    assert.assertHasFunction(methods, "maxOfCitizens")
end)
suite:test("colony_integrator methods are callable", function()
    local methods = mod.types["colony_integrator"]
    assert.assertCalls(methods["amountOfCitizens"])
    assert.assertCalls(methods["amountOfConstructionSites"])
    assert.assertCalls(methods["amountOfGraves"])
    assert.assertCalls(methods["getBuilderResources"])
    assert.assertCalls(methods["getBuildings"])
    assert.assertCalls(methods["getCitizens"])
    assert.assertCalls(methods["getColonyID"])
    assert.assertCalls(methods["getColonyName"])
    assert.assertCalls(methods["getColonyStyle"])
    assert.assertCalls(methods["getHappiness"])
    assert.assertCalls(methods["getLocation"])
    assert.assertCalls(methods["getName"])
    assert.assertCalls(methods["getRequests"])
    assert.assertCalls(methods["getResearch"])
    assert.assertCalls(methods["getVisitors"])
    assert.assertCalls(methods["getWorkOrderResources"])
    assert.assertCalls(methods["getWorkOrders"])
    assert.assertCalls(methods["isActive"])
    assert.assertCalls(methods["isInColony"])
    assert.assertCalls(methods["isUnderAttack"])
    assert.assertCalls(methods["isUnderRaid"])
    assert.assertCalls(methods["isWithin"])
    assert.assertCalls(methods["maxOfCitizens"])
end)
suite:test("colony_integrator stub return types", function()
    local methods = mod.types["colony_integrator"]
    assert.assertType(methods["amountOfCitizens"](), "number")
    assert.assertType(methods["amountOfConstructionSites"](), "number")
    assert.assertType(methods["amountOfGraves"](), "number")
    assert.assertType(methods["getColonyID"](), "number")
    assert.assertType(methods["getColonyName"](), "string")
    assert.assertType(methods["getColonyStyle"](), "string")
    assert.assertType(methods["getHappiness"](), "number")
    assert.assertType(methods["getName"](), "string")
    assert.assertType(methods["isActive"](), "boolean")
    assert.assertType(methods["isInColony"](), "boolean")
    assert.assertType(methods["isUnderAttack"](), "boolean")
    assert.assertType(methods["isUnderRaid"](), "boolean")
    assert.assertType(methods["isWithin"](), "boolean")
    assert.assertType(methods["maxOfCitizens"](), "number")
end)
suite:test("type compass exists", function()
    assert.assertType(mod.types["compass"], "table")
end)
suite:test("compass exposes 2 methods", function()
    local methods = mod.types["compass"]
    assert.assertHasFunction(methods, "getFacing")
    assert.assertHasFunction(methods, "getName")
end)
suite:test("compass methods are callable", function()
    local methods = mod.types["compass"]
    assert.assertCalls(methods["getFacing"])
    assert.assertCalls(methods["getName"])
end)
suite:test("compass stub return types", function()
    local methods = mod.types["compass"]
    assert.assertType(methods["getFacing"](), "string")
    assert.assertType(methods["getName"](), "string")
end)
suite:test("type end_automata exists", function()
    assert.assertType(mod.types["end_automata"], "table")
end)
suite:test("end_automata exposes 6 methods", function()
    local methods = mod.types["end_automata"]
    assert.assertHasFunction(methods, "deletePoint")
    assert.assertHasFunction(methods, "distanceToPoint")
    assert.assertHasFunction(methods, "estimateWarpCost")
    assert.assertHasFunction(methods, "points")
    assert.assertHasFunction(methods, "savePoint")
    assert.assertHasFunction(methods, "warpToPoint")
end)
suite:test("end_automata methods are callable", function()
    local methods = mod.types["end_automata"]
    assert.assertCalls(methods["deletePoint"])
    assert.assertCalls(methods["distanceToPoint"])
    assert.assertCalls(methods["estimateWarpCost"])
    assert.assertCalls(methods["points"])
    assert.assertCalls(methods["savePoint"])
    assert.assertCalls(methods["warpToPoint"])
end)
suite:test("end_automata stub return types", function()
    local methods = mod.types["end_automata"]
    assert.assertType(methods["deletePoint"](), "table")
    assert.assertType(methods["distanceToPoint"](), "table")
    assert.assertType(methods["estimateWarpCost"](), "table")
    assert.assertType(methods["points"](), "table")
    assert.assertType(methods["savePoint"](), "table")
    assert.assertType(methods["warpToPoint"](), "table")
end)
suite:test("type energy_detector exists", function()
    assert.assertType(mod.types["energy_detector"], "table")
end)
suite:test("energy_detector exposes 4 methods", function()
    local methods = mod.types["energy_detector"]
    assert.assertHasFunction(methods, "getName")
    assert.assertHasFunction(methods, "getTransferRate")
    assert.assertHasFunction(methods, "getTransferRateLimit")
    assert.assertHasFunction(methods, "setTransferRateLimit")
end)
suite:test("energy_detector methods are callable", function()
    local methods = mod.types["energy_detector"]
    assert.assertCalls(methods["getName"])
    assert.assertCalls(methods["getTransferRate"])
    assert.assertCalls(methods["getTransferRateLimit"])
    assert.assertCalls(methods["setTransferRateLimit"])
end)
suite:test("energy_detector stub return types", function()
    local methods = mod.types["energy_detector"]
    assert.assertType(methods["getName"](), "string")
    assert.assertType(methods["getTransferRate"](), "number")
    assert.assertType(methods["getTransferRateLimit"](), "number")
end)
suite:test("type environment_detector exists", function()
    assert.assertType(mod.types["environment_detector"], "table")
end)
suite:test("environment_detector exposes 20 methods", function()
    local methods = mod.types["environment_detector"]
    assert.assertHasFunction(methods, "canSleepHere")
    assert.assertHasFunction(methods, "canSleepPlayer")
    assert.assertHasFunction(methods, "getBiome")
    assert.assertHasFunction(methods, "getBlockLightLevel")
    assert.assertHasFunction(methods, "getDayLightLevel")
    assert.assertHasFunction(methods, "getDimension")
    assert.assertHasFunction(methods, "getMoonId")
    assert.assertHasFunction(methods, "getMoonName")
    assert.assertHasFunction(methods, "getName")
    assert.assertHasFunction(methods, "getSkyLightLevel")
    assert.assertHasFunction(methods, "getTime")
    assert.assertHasFunction(methods, "isDimension")
    assert.assertHasFunction(methods, "isMoon")
    assert.assertHasFunction(methods, "isRaining")
    assert.assertHasFunction(methods, "isSlimeChunk")
    assert.assertHasFunction(methods, "isSunny")
    assert.assertHasFunction(methods, "isThunder")
    assert.assertHasFunction(methods, "listDimensions")
    assert.assertHasFunction(methods, "scanCost")
    assert.assertHasFunction(methods, "scanEntities")
end)
suite:test("environment_detector methods are callable", function()
    local methods = mod.types["environment_detector"]
    assert.assertCalls(methods["canSleepHere"])
    assert.assertCalls(methods["canSleepPlayer"])
    assert.assertCalls(methods["getBiome"])
    assert.assertCalls(methods["getBlockLightLevel"])
    assert.assertCalls(methods["getDayLightLevel"])
    assert.assertCalls(methods["getDimension"])
    assert.assertCalls(methods["getMoonId"])
    assert.assertCalls(methods["getMoonName"])
    assert.assertCalls(methods["getName"])
    assert.assertCalls(methods["getSkyLightLevel"])
    assert.assertCalls(methods["getTime"])
    assert.assertCalls(methods["isDimension"])
    assert.assertCalls(methods["isMoon"])
    assert.assertCalls(methods["isRaining"])
    assert.assertCalls(methods["isSlimeChunk"])
    assert.assertCalls(methods["isSunny"])
    assert.assertCalls(methods["isThunder"])
    assert.assertCalls(methods["listDimensions"])
    assert.assertCalls(methods["scanCost"])
    assert.assertCalls(methods["scanEntities"])
end)
suite:test("environment_detector stub return types", function()
    local methods = mod.types["environment_detector"]
    assert.assertType(methods["canSleepHere"](), "table")
    assert.assertType(methods["canSleepPlayer"](), "table")
    assert.assertType(methods["getBiome"](), "string")
    assert.assertType(methods["getBlockLightLevel"](), "number")
    assert.assertType(methods["getDayLightLevel"](), "number")
    assert.assertType(methods["getDimension"](), "string")
    assert.assertType(methods["getMoonId"](), "number")
    assert.assertType(methods["getMoonName"](), "string")
    assert.assertType(methods["getName"](), "string")
    assert.assertType(methods["getSkyLightLevel"](), "number")
    assert.assertType(methods["getTime"](), "number")
    assert.assertType(methods["isDimension"](), "boolean")
    assert.assertType(methods["isMoon"](), "boolean")
    assert.assertType(methods["isRaining"](), "boolean")
    assert.assertType(methods["isSlimeChunk"](), "boolean")
    assert.assertType(methods["isSunny"](), "boolean")
    assert.assertType(methods["isThunder"](), "boolean")
    assert.assertType(methods["listDimensions"](), "table")
    assert.assertType(methods["scanCost"](), "table")
    assert.assertType(methods["scanEntities"](), "table")
end)
suite:test("type geo_scanner exists", function()
    assert.assertType(mod.types["geo_scanner"], "table")
end)
suite:test("geo_scanner exposes 4 methods", function()
    local methods = mod.types["geo_scanner"]
    assert.assertHasFunction(methods, "chunkAnalyze")
    assert.assertHasFunction(methods, "cost")
    assert.assertHasFunction(methods, "getName")
    assert.assertHasFunction(methods, "scan")
end)
suite:test("geo_scanner methods are callable", function()
    local methods = mod.types["geo_scanner"]
    assert.assertCalls(methods["chunkAnalyze"])
    assert.assertCalls(methods["cost"])
    assert.assertCalls(methods["getName"])
    assert.assertCalls(methods["scan"])
end)
suite:test("geo_scanner stub return types", function()
    local methods = mod.types["geo_scanner"]
    assert.assertType(methods["chunkAnalyze"](), "table")
    assert.assertType(methods["cost"](), "table")
    assert.assertType(methods["getName"](), "string")
    assert.assertType(methods["scan"](), "table")
end)
suite:test("type husbandry_automata exists", function()
    assert.assertType(mod.types["husbandry_automata"], "table")
end)
suite:test("husbandry_automata exposes 6 methods", function()
    local methods = mod.types["husbandry_automata"]
    assert.assertHasFunction(methods, "captureAnimal")
    assert.assertHasFunction(methods, "getCapturedAnimal")
    assert.assertHasFunction(methods, "inspectAnimal")
    assert.assertHasFunction(methods, "releaseAnimal")
    assert.assertHasFunction(methods, "searchAnimals")
    assert.assertHasFunction(methods, "useOnAnimal")
end)
suite:test("husbandry_automata methods are callable", function()
    local methods = mod.types["husbandry_automata"]
    assert.assertCalls(methods["captureAnimal"])
    assert.assertCalls(methods["getCapturedAnimal"])
    assert.assertCalls(methods["inspectAnimal"])
    assert.assertCalls(methods["releaseAnimal"])
    assert.assertCalls(methods["searchAnimals"])
    assert.assertCalls(methods["useOnAnimal"])
end)
suite:test("husbandry_automata stub return types", function()
    local methods = mod.types["husbandry_automata"]
    assert.assertType(methods["captureAnimal"](), "table")
    assert.assertType(methods["getCapturedAnimal"](), "table")
    assert.assertType(methods["inspectAnimal"](), "table")
    assert.assertType(methods["releaseAnimal"](), "table")
    assert.assertType(methods["searchAnimals"](), "table")
    assert.assertType(methods["useOnAnimal"](), "table")
end)
suite:test("type inventory_manager exists", function()
    assert.assertType(mod.types["inventory_manager"], "table")
end)
suite:test("inventory_manager exposes 14 methods", function()
    local methods = mod.types["inventory_manager"]
    assert.assertHasFunction(methods, "addItemToPlayer")
    assert.assertHasFunction(methods, "getArmor")
    assert.assertHasFunction(methods, "getEmptySpace")
    assert.assertHasFunction(methods, "getFreeSlot")
    assert.assertHasFunction(methods, "getItems")
    assert.assertHasFunction(methods, "getItemsChest")
    assert.assertHasFunction(methods, "getName")
    assert.assertHasFunction(methods, "getOwner")
    assert.assertHasFunction(methods, "isPlayerEquipped")
    assert.assertHasFunction(methods, "isSpaceAvailable")
    assert.assertHasFunction(methods, "isWearing")
    assert.assertHasFunction(methods, "list")
    assert.assertHasFunction(methods, "listChest")
    assert.assertHasFunction(methods, "removeItemFromPlayer")
end)
suite:test("inventory_manager methods are callable", function()
    local methods = mod.types["inventory_manager"]
    assert.assertCalls(methods["addItemToPlayer"])
    assert.assertCalls(methods["getArmor"])
    assert.assertCalls(methods["getEmptySpace"])
    assert.assertCalls(methods["getFreeSlot"])
    assert.assertCalls(methods["getItems"])
    assert.assertCalls(methods["getItemsChest"])
    assert.assertCalls(methods["getName"])
    assert.assertCalls(methods["getOwner"])
    assert.assertCalls(methods["isPlayerEquipped"])
    assert.assertCalls(methods["isSpaceAvailable"])
    assert.assertCalls(methods["isWearing"])
    assert.assertCalls(methods["list"])
    assert.assertCalls(methods["listChest"])
    assert.assertCalls(methods["removeItemFromPlayer"])
end)
suite:test("inventory_manager stub return types", function()
    local methods = mod.types["inventory_manager"]
    assert.assertType(methods["addItemToPlayer"](), "table")
    assert.assertType(methods["getArmor"](), "table")
    assert.assertType(methods["getEmptySpace"](), "number")
    assert.assertType(methods["getFreeSlot"](), "number")
    assert.assertType(methods["getItems"](), "table")
    assert.assertType(methods["getItemsChest"](), "table")
    assert.assertType(methods["getName"](), "string")
    assert.assertType(methods["getOwner"](), "string")
    assert.assertType(methods["isPlayerEquipped"](), "boolean")
    assert.assertType(methods["isSpaceAvailable"](), "boolean")
    assert.assertType(methods["isWearing"](), "boolean")
    assert.assertType(methods["list"](), "table")
    assert.assertType(methods["listChest"](), "table")
    assert.assertType(methods["removeItemFromPlayer"](), "table")
end)
suite:test("type me_bridge exists", function()
    assert.assertType(mod.types["me_bridge"], "table")
end)
suite:test("me_bridge exposes 50 methods", function()
    local methods = mod.types["me_bridge"]
    assert.assertHasFunction(methods, "cancelCraftingTasks")
    assert.assertHasFunction(methods, "craftFluid")
    assert.assertHasFunction(methods, "craftItem")
    assert.assertHasFunction(methods, "exportChemical")
    assert.assertHasFunction(methods, "exportFluid")
    assert.assertHasFunction(methods, "exportItem")
    assert.assertHasFunction(methods, "getAvailableChemicalStorage")
    assert.assertHasFunction(methods, "getAvailableExternalChemicalStorage")
    assert.assertHasFunction(methods, "getAvailableExternalFluidStorage")
    assert.assertHasFunction(methods, "getAvailableExternalItemStorage")
    assert.assertHasFunction(methods, "getAvailableFluidStorage")
    assert.assertHasFunction(methods, "getAvailableItemStorage")
    assert.assertHasFunction(methods, "getAverageEnergyInput")
    assert.assertHasFunction(methods, "getCells")
    assert.assertHasFunction(methods, "getChemical")
    assert.assertHasFunction(methods, "getChemicals")
    assert.assertHasFunction(methods, "getCraftableFluids")
    assert.assertHasFunction(methods, "getCraftableItems")
    assert.assertHasFunction(methods, "getCraftingCPUs")
    assert.assertHasFunction(methods, "getCraftingTask")
    assert.assertHasFunction(methods, "getCraftingTasks")
    assert.assertHasFunction(methods, "getDrives")
    assert.assertHasFunction(methods, "getEnergyCapacity")
    assert.assertHasFunction(methods, "getEnergyUsage")
    assert.assertHasFunction(methods, "getFluid")
    assert.assertHasFunction(methods, "getFluids")
    assert.assertHasFunction(methods, "getItem")
    assert.assertHasFunction(methods, "getItems")
    assert.assertHasFunction(methods, "getName")
    assert.assertHasFunction(methods, "getPatterns")
    assert.assertHasFunction(methods, "getStoredEnergy")
    assert.assertHasFunction(methods, "getTotalChemicalStorage")
    assert.assertHasFunction(methods, "getTotalExternalChemicalStorage")
    assert.assertHasFunction(methods, "getTotalExternalFluidStorage")
    assert.assertHasFunction(methods, "getTotalExternalItemStorage")
    assert.assertHasFunction(methods, "getTotalFluidStorage")
    assert.assertHasFunction(methods, "getTotalItemStorage")
    assert.assertHasFunction(methods, "getUsedChemicalStorage")
    assert.assertHasFunction(methods, "getUsedExternalChemicalStorage")
    assert.assertHasFunction(methods, "getUsedExternalFluidStorage")
    assert.assertHasFunction(methods, "getUsedExternalItemStorage")
    assert.assertHasFunction(methods, "getUsedFluidStorage")
    assert.assertHasFunction(methods, "getUsedItemStorage")
    assert.assertHasFunction(methods, "importChemical")
    assert.assertHasFunction(methods, "importFluid")
    assert.assertHasFunction(methods, "importItem")
    assert.assertHasFunction(methods, "isConnected")
    assert.assertHasFunction(methods, "isCraftable")
    assert.assertHasFunction(methods, "isCrafting")
    assert.assertHasFunction(methods, "isOnline")
end)
suite:test("me_bridge methods are callable", function()
    local methods = mod.types["me_bridge"]
    assert.assertCalls(methods["cancelCraftingTasks"])
    assert.assertCalls(methods["craftFluid"])
    assert.assertCalls(methods["craftItem"])
    assert.assertCalls(methods["exportChemical"])
    assert.assertCalls(methods["exportFluid"])
    assert.assertCalls(methods["exportItem"])
    assert.assertCalls(methods["getAvailableChemicalStorage"])
    assert.assertCalls(methods["getAvailableExternalChemicalStorage"])
    assert.assertCalls(methods["getAvailableExternalFluidStorage"])
    assert.assertCalls(methods["getAvailableExternalItemStorage"])
    assert.assertCalls(methods["getAvailableFluidStorage"])
    assert.assertCalls(methods["getAvailableItemStorage"])
    assert.assertCalls(methods["getAverageEnergyInput"])
    assert.assertCalls(methods["getCells"])
    assert.assertCalls(methods["getChemical"])
    assert.assertCalls(methods["getChemicals"])
    assert.assertCalls(methods["getCraftableFluids"])
    assert.assertCalls(methods["getCraftableItems"])
    assert.assertCalls(methods["getCraftingCPUs"])
    assert.assertCalls(methods["getCraftingTask"])
    assert.assertCalls(methods["getCraftingTasks"])
    assert.assertCalls(methods["getDrives"])
    assert.assertCalls(methods["getEnergyCapacity"])
    assert.assertCalls(methods["getEnergyUsage"])
    assert.assertCalls(methods["getFluid"])
    assert.assertCalls(methods["getFluids"])
    assert.assertCalls(methods["getItem"])
    assert.assertCalls(methods["getItems"])
    assert.assertCalls(methods["getName"])
    assert.assertCalls(methods["getPatterns"])
    assert.assertCalls(methods["getStoredEnergy"])
    assert.assertCalls(methods["getTotalChemicalStorage"])
    assert.assertCalls(methods["getTotalExternalChemicalStorage"])
    assert.assertCalls(methods["getTotalExternalFluidStorage"])
    assert.assertCalls(methods["getTotalExternalItemStorage"])
    assert.assertCalls(methods["getTotalFluidStorage"])
    assert.assertCalls(methods["getTotalItemStorage"])
    assert.assertCalls(methods["getUsedChemicalStorage"])
    assert.assertCalls(methods["getUsedExternalChemicalStorage"])
    assert.assertCalls(methods["getUsedExternalFluidStorage"])
    assert.assertCalls(methods["getUsedExternalItemStorage"])
    assert.assertCalls(methods["getUsedFluidStorage"])
    assert.assertCalls(methods["getUsedItemStorage"])
    assert.assertCalls(methods["importChemical"])
    assert.assertCalls(methods["importFluid"])
    assert.assertCalls(methods["importItem"])
    assert.assertCalls(methods["isConnected"])
    assert.assertCalls(methods["isCraftable"])
    assert.assertCalls(methods["isCrafting"])
    assert.assertCalls(methods["isOnline"])
end)
suite:test("me_bridge stub return types", function()
    local methods = mod.types["me_bridge"]
    assert.assertType(methods["cancelCraftingTasks"](), "table")
    assert.assertType(methods["craftFluid"](), "table")
    assert.assertType(methods["craftItem"](), "table")
    assert.assertType(methods["exportChemical"](), "table")
    assert.assertType(methods["exportFluid"](), "table")
    assert.assertType(methods["exportItem"](), "table")
    assert.assertType(methods["getAvailableChemicalStorage"](), "table")
    assert.assertType(methods["getAvailableExternalChemicalStorage"](), "table")
    assert.assertType(methods["getAvailableExternalFluidStorage"](), "table")
    assert.assertType(methods["getAvailableExternalItemStorage"](), "table")
    assert.assertType(methods["getAvailableFluidStorage"](), "table")
    assert.assertType(methods["getAvailableItemStorage"](), "table")
    assert.assertType(methods["getAverageEnergyInput"](), "table")
    assert.assertType(methods["getCells"](), "table")
    assert.assertType(methods["getChemical"](), "table")
    assert.assertType(methods["getChemicals"](), "table")
    assert.assertType(methods["getCraftableFluids"](), "table")
    assert.assertType(methods["getCraftableItems"](), "table")
    assert.assertType(methods["getCraftingCPUs"](), "table")
    assert.assertType(methods["getCraftingTask"](), "table")
    assert.assertType(methods["getCraftingTasks"](), "table")
    assert.assertType(methods["getDrives"](), "table")
    assert.assertType(methods["getEnergyCapacity"](), "table")
    assert.assertType(methods["getEnergyUsage"](), "table")
    assert.assertType(methods["getFluid"](), "table")
    assert.assertType(methods["getFluids"](), "table")
    assert.assertType(methods["getItem"](), "table")
    assert.assertType(methods["getItems"](), "table")
    assert.assertType(methods["getName"](), "string")
    assert.assertType(methods["getPatterns"](), "table")
    assert.assertType(methods["getStoredEnergy"](), "table")
    assert.assertType(methods["getTotalChemicalStorage"](), "table")
    assert.assertType(methods["getTotalExternalChemicalStorage"](), "table")
    assert.assertType(methods["getTotalExternalFluidStorage"](), "table")
    assert.assertType(methods["getTotalExternalItemStorage"](), "table")
    assert.assertType(methods["getTotalFluidStorage"](), "table")
    assert.assertType(methods["getTotalItemStorage"](), "table")
    assert.assertType(methods["getUsedChemicalStorage"](), "table")
    assert.assertType(methods["getUsedExternalChemicalStorage"](), "table")
    assert.assertType(methods["getUsedExternalFluidStorage"](), "table")
    assert.assertType(methods["getUsedExternalItemStorage"](), "table")
    assert.assertType(methods["getUsedFluidStorage"](), "table")
    assert.assertType(methods["getUsedItemStorage"](), "table")
    assert.assertType(methods["importChemical"](), "table")
    assert.assertType(methods["importFluid"](), "table")
    assert.assertType(methods["importItem"](), "table")
    assert.assertType(methods["isConnected"](), "boolean")
    assert.assertType(methods["isCraftable"](), "table")
    assert.assertType(methods["isCrafting"](), "table")
    assert.assertType(methods["isOnline"](), "table")
end)
suite:test("type nbt_storage exists", function()
    assert.assertType(mod.types["nbt_storage"], "table")
end)
suite:test("nbt_storage exposes 4 methods", function()
    local methods = mod.types["nbt_storage"]
    assert.assertHasFunction(methods, "getName")
    assert.assertHasFunction(methods, "read")
    assert.assertHasFunction(methods, "writeJson")
    assert.assertHasFunction(methods, "writeTable")
end)
suite:test("nbt_storage methods are callable", function()
    local methods = mod.types["nbt_storage"]
    assert.assertCalls(methods["getName"])
    assert.assertCalls(methods["read"])
    assert.assertCalls(methods["writeJson"])
    assert.assertCalls(methods["writeTable"])
end)
suite:test("nbt_storage stub return types", function()
    local methods = mod.types["nbt_storage"]
    assert.assertType(methods["getName"](), "string")
    assert.assertType(methods["read"](), "table")
    assert.assertType(methods["writeJson"](), "table")
    assert.assertType(methods["writeTable"](), "table")
end)
suite:test("type overpowered_end_automata exists", function()
    assert.assertType(mod.types["overpowered_end_automata"], "table")
end)
suite:test("overpowered_end_automata exposes 6 methods", function()
    local methods = mod.types["overpowered_end_automata"]
    assert.assertHasFunction(methods, "deletePoint")
    assert.assertHasFunction(methods, "distanceToPoint")
    assert.assertHasFunction(methods, "estimateWarpCost")
    assert.assertHasFunction(methods, "points")
    assert.assertHasFunction(methods, "savePoint")
    assert.assertHasFunction(methods, "warpToPoint")
end)
suite:test("overpowered_end_automata methods are callable", function()
    local methods = mod.types["overpowered_end_automata"]
    assert.assertCalls(methods["deletePoint"])
    assert.assertCalls(methods["distanceToPoint"])
    assert.assertCalls(methods["estimateWarpCost"])
    assert.assertCalls(methods["points"])
    assert.assertCalls(methods["savePoint"])
    assert.assertCalls(methods["warpToPoint"])
end)
suite:test("overpowered_end_automata stub return types", function()
    local methods = mod.types["overpowered_end_automata"]
    assert.assertType(methods["deletePoint"](), "table")
    assert.assertType(methods["distanceToPoint"](), "table")
    assert.assertType(methods["estimateWarpCost"](), "table")
    assert.assertType(methods["points"](), "table")
    assert.assertType(methods["savePoint"](), "table")
    assert.assertType(methods["warpToPoint"](), "table")
end)
suite:test("type overpowered_husbandry_automata exists", function()
    assert.assertType(mod.types["overpowered_husbandry_automata"], "table")
end)
suite:test("overpowered_husbandry_automata exposes 6 methods", function()
    local methods = mod.types["overpowered_husbandry_automata"]
    assert.assertHasFunction(methods, "captureAnimal")
    assert.assertHasFunction(methods, "getCapturedAnimal")
    assert.assertHasFunction(methods, "inspectAnimal")
    assert.assertHasFunction(methods, "releaseAnimal")
    assert.assertHasFunction(methods, "searchAnimals")
    assert.assertHasFunction(methods, "useOnAnimal")
end)
suite:test("overpowered_husbandry_automata methods are callable", function()
    local methods = mod.types["overpowered_husbandry_automata"]
    assert.assertCalls(methods["captureAnimal"])
    assert.assertCalls(methods["getCapturedAnimal"])
    assert.assertCalls(methods["inspectAnimal"])
    assert.assertCalls(methods["releaseAnimal"])
    assert.assertCalls(methods["searchAnimals"])
    assert.assertCalls(methods["useOnAnimal"])
end)
suite:test("overpowered_husbandry_automata stub return types", function()
    local methods = mod.types["overpowered_husbandry_automata"]
    assert.assertType(methods["captureAnimal"](), "table")
    assert.assertType(methods["getCapturedAnimal"](), "table")
    assert.assertType(methods["inspectAnimal"](), "table")
    assert.assertType(methods["releaseAnimal"](), "table")
    assert.assertType(methods["searchAnimals"](), "table")
    assert.assertType(methods["useOnAnimal"](), "table")
end)
suite:test("type overpowered_weak_automata exists", function()
    assert.assertType(mod.types["overpowered_weak_automata"], "table")
end)
suite:test("overpowered_weak_automata exposes 10 methods", function()
    local methods = mod.types["overpowered_weak_automata"]
    assert.assertHasFunction(methods, "chargeTurtle")
    assert.assertHasFunction(methods, "collectItems")
    assert.assertHasFunction(methods, "collectSpecificItem")
    assert.assertHasFunction(methods, "digBlock")
    assert.assertHasFunction(methods, "feedSoul")
    assert.assertHasFunction(methods, "lookAtBlock")
    assert.assertHasFunction(methods, "lookAtEntity")
    assert.assertHasFunction(methods, "placeBlock")
    assert.assertHasFunction(methods, "scanItems")
    assert.assertHasFunction(methods, "useOnBlock")
end)
suite:test("overpowered_weak_automata methods are callable", function()
    local methods = mod.types["overpowered_weak_automata"]
    assert.assertCalls(methods["chargeTurtle"])
    assert.assertCalls(methods["collectItems"])
    assert.assertCalls(methods["collectSpecificItem"])
    assert.assertCalls(methods["digBlock"])
    assert.assertCalls(methods["feedSoul"])
    assert.assertCalls(methods["lookAtBlock"])
    assert.assertCalls(methods["lookAtEntity"])
    assert.assertCalls(methods["placeBlock"])
    assert.assertCalls(methods["scanItems"])
    assert.assertCalls(methods["useOnBlock"])
end)
suite:test("overpowered_weak_automata stub return types", function()
    local methods = mod.types["overpowered_weak_automata"]
    assert.assertType(methods["chargeTurtle"](), "table")
    assert.assertType(methods["collectItems"](), "table")
    assert.assertType(methods["collectSpecificItem"](), "table")
    assert.assertType(methods["digBlock"](), "table")
    assert.assertType(methods["feedSoul"](), "table")
    assert.assertType(methods["lookAtBlock"](), "table")
    assert.assertType(methods["lookAtEntity"](), "table")
    assert.assertType(methods["placeBlock"](), "table")
    assert.assertType(methods["scanItems"](), "table")
    assert.assertType(methods["useOnBlock"](), "table")
end)
suite:test("type player_detector exists", function()
    assert.assertType(mod.types["player_detector"], "table")
end)
suite:test("player_detector exposes 11 methods", function()
    local methods = mod.types["player_detector"]
    assert.assertHasFunction(methods, "getName")
    assert.assertHasFunction(methods, "getOnlinePlayers")
    assert.assertHasFunction(methods, "getPlayersInCoords")
    assert.assertHasFunction(methods, "getPlayersInCubic")
    assert.assertHasFunction(methods, "getPlayersInRange")
    assert.assertHasFunction(methods, "isPlayerInCoords")
    assert.assertHasFunction(methods, "isPlayerInCubic")
    assert.assertHasFunction(methods, "isPlayerInRange")
    assert.assertHasFunction(methods, "isPlayersInCoords")
    assert.assertHasFunction(methods, "isPlayersInCubic")
    assert.assertHasFunction(methods, "isPlayersInRange")
end)
suite:test("player_detector methods are callable", function()
    local methods = mod.types["player_detector"]
    assert.assertCalls(methods["getName"])
    assert.assertCalls(methods["getOnlinePlayers"])
    assert.assertCalls(methods["getPlayersInCoords"])
    assert.assertCalls(methods["getPlayersInCubic"])
    assert.assertCalls(methods["getPlayersInRange"])
    assert.assertCalls(methods["isPlayerInCoords"])
    assert.assertCalls(methods["isPlayerInCubic"])
    assert.assertCalls(methods["isPlayerInRange"])
    assert.assertCalls(methods["isPlayersInCoords"])
    assert.assertCalls(methods["isPlayersInCubic"])
    assert.assertCalls(methods["isPlayersInRange"])
end)
suite:test("player_detector stub return types", function()
    local methods = mod.types["player_detector"]
    assert.assertType(methods["getName"](), "string")
    assert.assertType(methods["getOnlinePlayers"](), "string")
    assert.assertType(methods["getPlayersInCoords"](), "table")
    assert.assertType(methods["getPlayersInCubic"](), "table")
    assert.assertType(methods["getPlayersInRange"](), "table")
    assert.assertType(methods["isPlayerInCoords"](), "boolean")
    assert.assertType(methods["isPlayerInCubic"](), "boolean")
    assert.assertType(methods["isPlayerInRange"](), "boolean")
    assert.assertType(methods["isPlayersInCoords"](), "boolean")
    assert.assertType(methods["isPlayersInCubic"](), "boolean")
    assert.assertType(methods["isPlayersInRange"](), "boolean")
end)
suite:test("type rs_bridge exists", function()
    assert.assertType(mod.types["rs_bridge"], "table")
end)
suite:test("rs_bridge exposes 51 methods", function()
    local methods = mod.types["rs_bridge"]
    assert.assertHasFunction(methods, "cancelCraftingTasks")
    assert.assertHasFunction(methods, "craftChemical")
    assert.assertHasFunction(methods, "craftFluid")
    assert.assertHasFunction(methods, "craftItem")
    assert.assertHasFunction(methods, "exportChemical")
    assert.assertHasFunction(methods, "exportFluid")
    assert.assertHasFunction(methods, "exportItem")
    assert.assertHasFunction(methods, "getAvailableChemicalStorage")
    assert.assertHasFunction(methods, "getAvailableExternalChemicalStorage")
    assert.assertHasFunction(methods, "getAvailableExternalFluidStorage")
    assert.assertHasFunction(methods, "getAvailableExternalItemStorage")
    assert.assertHasFunction(methods, "getAvailableFluidStorage")
    assert.assertHasFunction(methods, "getAvailableItemStorage")
    assert.assertHasFunction(methods, "getAverageEnergyInput")
    assert.assertHasFunction(methods, "getCells")
    assert.assertHasFunction(methods, "getChemical")
    assert.assertHasFunction(methods, "getChemicals")
    assert.assertHasFunction(methods, "getCraftableChemicals")
    assert.assertHasFunction(methods, "getCraftableFluids")
    assert.assertHasFunction(methods, "getCraftableItems")
    assert.assertHasFunction(methods, "getCraftingTask")
    assert.assertHasFunction(methods, "getCraftingTasks")
    assert.assertHasFunction(methods, "getDrives")
    assert.assertHasFunction(methods, "getEnergyCapacity")
    assert.assertHasFunction(methods, "getEnergyUsage")
    assert.assertHasFunction(methods, "getFluid")
    assert.assertHasFunction(methods, "getFluids")
    assert.assertHasFunction(methods, "getItem")
    assert.assertHasFunction(methods, "getItems")
    assert.assertHasFunction(methods, "getName")
    assert.assertHasFunction(methods, "getPatterns")
    assert.assertHasFunction(methods, "getStoredEnergy")
    assert.assertHasFunction(methods, "getTotalChemicalStorage")
    assert.assertHasFunction(methods, "getTotalExternalChemicalStorage")
    assert.assertHasFunction(methods, "getTotalExternalFluidStorage")
    assert.assertHasFunction(methods, "getTotalExternalItemStorage")
    assert.assertHasFunction(methods, "getTotalFluidStorage")
    assert.assertHasFunction(methods, "getTotalItemStorage")
    assert.assertHasFunction(methods, "getUsedChemicalStorage")
    assert.assertHasFunction(methods, "getUsedExternalChemicalStorage")
    assert.assertHasFunction(methods, "getUsedExternalFluidStorage")
    assert.assertHasFunction(methods, "getUsedExternalItemStorage")
    assert.assertHasFunction(methods, "getUsedFluidStorage")
    assert.assertHasFunction(methods, "getUsedItemStorage")
    assert.assertHasFunction(methods, "importChemical")
    assert.assertHasFunction(methods, "importFluid")
    assert.assertHasFunction(methods, "importItem")
    assert.assertHasFunction(methods, "isConnected")
    assert.assertHasFunction(methods, "isCraftable")
    assert.assertHasFunction(methods, "isCrafting")
    assert.assertHasFunction(methods, "isOnline")
end)
suite:test("rs_bridge methods are callable", function()
    local methods = mod.types["rs_bridge"]
    assert.assertCalls(methods["cancelCraftingTasks"])
    assert.assertCalls(methods["craftChemical"])
    assert.assertCalls(methods["craftFluid"])
    assert.assertCalls(methods["craftItem"])
    assert.assertCalls(methods["exportChemical"])
    assert.assertCalls(methods["exportFluid"])
    assert.assertCalls(methods["exportItem"])
    assert.assertCalls(methods["getAvailableChemicalStorage"])
    assert.assertCalls(methods["getAvailableExternalChemicalStorage"])
    assert.assertCalls(methods["getAvailableExternalFluidStorage"])
    assert.assertCalls(methods["getAvailableExternalItemStorage"])
    assert.assertCalls(methods["getAvailableFluidStorage"])
    assert.assertCalls(methods["getAvailableItemStorage"])
    assert.assertCalls(methods["getAverageEnergyInput"])
    assert.assertCalls(methods["getCells"])
    assert.assertCalls(methods["getChemical"])
    assert.assertCalls(methods["getChemicals"])
    assert.assertCalls(methods["getCraftableChemicals"])
    assert.assertCalls(methods["getCraftableFluids"])
    assert.assertCalls(methods["getCraftableItems"])
    assert.assertCalls(methods["getCraftingTask"])
    assert.assertCalls(methods["getCraftingTasks"])
    assert.assertCalls(methods["getDrives"])
    assert.assertCalls(methods["getEnergyCapacity"])
    assert.assertCalls(methods["getEnergyUsage"])
    assert.assertCalls(methods["getFluid"])
    assert.assertCalls(methods["getFluids"])
    assert.assertCalls(methods["getItem"])
    assert.assertCalls(methods["getItems"])
    assert.assertCalls(methods["getName"])
    assert.assertCalls(methods["getPatterns"])
    assert.assertCalls(methods["getStoredEnergy"])
    assert.assertCalls(methods["getTotalChemicalStorage"])
    assert.assertCalls(methods["getTotalExternalChemicalStorage"])
    assert.assertCalls(methods["getTotalExternalFluidStorage"])
    assert.assertCalls(methods["getTotalExternalItemStorage"])
    assert.assertCalls(methods["getTotalFluidStorage"])
    assert.assertCalls(methods["getTotalItemStorage"])
    assert.assertCalls(methods["getUsedChemicalStorage"])
    assert.assertCalls(methods["getUsedExternalChemicalStorage"])
    assert.assertCalls(methods["getUsedExternalFluidStorage"])
    assert.assertCalls(methods["getUsedExternalItemStorage"])
    assert.assertCalls(methods["getUsedFluidStorage"])
    assert.assertCalls(methods["getUsedItemStorage"])
    assert.assertCalls(methods["importChemical"])
    assert.assertCalls(methods["importFluid"])
    assert.assertCalls(methods["importItem"])
    assert.assertCalls(methods["isConnected"])
    assert.assertCalls(methods["isCraftable"])
    assert.assertCalls(methods["isCrafting"])
    assert.assertCalls(methods["isOnline"])
end)
suite:test("rs_bridge stub return types", function()
    local methods = mod.types["rs_bridge"]
    assert.assertType(methods["cancelCraftingTasks"](), "table")
    assert.assertType(methods["craftChemical"](), "table")
    assert.assertType(methods["craftFluid"](), "table")
    assert.assertType(methods["craftItem"](), "table")
    assert.assertType(methods["exportChemical"](), "table")
    assert.assertType(methods["exportFluid"](), "table")
    assert.assertType(methods["exportItem"](), "table")
    assert.assertType(methods["getAvailableChemicalStorage"](), "table")
    assert.assertType(methods["getAvailableExternalChemicalStorage"](), "table")
    assert.assertType(methods["getAvailableExternalFluidStorage"](), "table")
    assert.assertType(methods["getAvailableExternalItemStorage"](), "table")
    assert.assertType(methods["getAvailableFluidStorage"](), "table")
    assert.assertType(methods["getAvailableItemStorage"](), "table")
    assert.assertType(methods["getAverageEnergyInput"](), "table")
    assert.assertType(methods["getCells"](), "table")
    assert.assertType(methods["getChemical"](), "table")
    assert.assertType(methods["getChemicals"](), "table")
    assert.assertType(methods["getCraftableChemicals"](), "table")
    assert.assertType(methods["getCraftableFluids"](), "table")
    assert.assertType(methods["getCraftableItems"](), "table")
    assert.assertType(methods["getCraftingTask"](), "table")
    assert.assertType(methods["getCraftingTasks"](), "table")
    assert.assertType(methods["getDrives"](), "table")
    assert.assertType(methods["getEnergyCapacity"](), "table")
    assert.assertType(methods["getEnergyUsage"](), "table")
    assert.assertType(methods["getFluid"](), "table")
    assert.assertType(methods["getFluids"](), "table")
    assert.assertType(methods["getItem"](), "table")
    assert.assertType(methods["getItems"](), "table")
    assert.assertType(methods["getName"](), "string")
    assert.assertType(methods["getPatterns"](), "table")
    assert.assertType(methods["getStoredEnergy"](), "table")
    assert.assertType(methods["getTotalChemicalStorage"](), "table")
    assert.assertType(methods["getTotalExternalChemicalStorage"](), "table")
    assert.assertType(methods["getTotalExternalFluidStorage"](), "table")
    assert.assertType(methods["getTotalExternalItemStorage"](), "table")
    assert.assertType(methods["getTotalFluidStorage"](), "table")
    assert.assertType(methods["getTotalItemStorage"](), "table")
    assert.assertType(methods["getUsedChemicalStorage"](), "table")
    assert.assertType(methods["getUsedExternalChemicalStorage"](), "table")
    assert.assertType(methods["getUsedExternalFluidStorage"](), "table")
    assert.assertType(methods["getUsedExternalItemStorage"](), "table")
    assert.assertType(methods["getUsedFluidStorage"](), "table")
    assert.assertType(methods["getUsedItemStorage"](), "table")
    assert.assertType(methods["importChemical"](), "table")
    assert.assertType(methods["importFluid"](), "table")
    assert.assertType(methods["importItem"](), "table")
    assert.assertType(methods["isConnected"](), "boolean")
    assert.assertType(methods["isCraftable"](), "table")
    assert.assertType(methods["isCrafting"](), "table")
    assert.assertType(methods["isOnline"](), "table")
end)
suite:test("type weak_automata exists", function()
    assert.assertType(mod.types["weak_automata"], "table")
end)
suite:test("weak_automata exposes 10 methods", function()
    local methods = mod.types["weak_automata"]
    assert.assertHasFunction(methods, "chargeTurtle")
    assert.assertHasFunction(methods, "collectItems")
    assert.assertHasFunction(methods, "collectSpecificItem")
    assert.assertHasFunction(methods, "digBlock")
    assert.assertHasFunction(methods, "feedSoul")
    assert.assertHasFunction(methods, "lookAtBlock")
    assert.assertHasFunction(methods, "lookAtEntity")
    assert.assertHasFunction(methods, "placeBlock")
    assert.assertHasFunction(methods, "scanItems")
    assert.assertHasFunction(methods, "useOnBlock")
end)
suite:test("weak_automata methods are callable", function()
    local methods = mod.types["weak_automata"]
    assert.assertCalls(methods["chargeTurtle"])
    assert.assertCalls(methods["collectItems"])
    assert.assertCalls(methods["collectSpecificItem"])
    assert.assertCalls(methods["digBlock"])
    assert.assertCalls(methods["feedSoul"])
    assert.assertCalls(methods["lookAtBlock"])
    assert.assertCalls(methods["lookAtEntity"])
    assert.assertCalls(methods["placeBlock"])
    assert.assertCalls(methods["scanItems"])
    assert.assertCalls(methods["useOnBlock"])
end)
suite:test("weak_automata stub return types", function()
    local methods = mod.types["weak_automata"]
    assert.assertType(methods["chargeTurtle"](), "table")
    assert.assertType(methods["collectItems"](), "table")
    assert.assertType(methods["collectSpecificItem"](), "table")
    assert.assertType(methods["digBlock"](), "table")
    assert.assertType(methods["feedSoul"](), "table")
    assert.assertType(methods["lookAtBlock"](), "table")
    assert.assertType(methods["lookAtEntity"](), "table")
    assert.assertType(methods["placeBlock"](), "table")
    assert.assertType(methods["scanItems"](), "table")
    assert.assertType(methods["useOnBlock"](), "table")
end)

local passed, failed = suite:summary()
return passed, failed
