-- tests/mock_api/test_create.lua
-- GENERATED completeness tests for mock_api/create.lua (from api-docs inventory).
-- Regenerate with gen_tests.py. Every peripheral type must exist, expose its
-- documented methods, and each method must be callable with no arguments.
-- Methods with deterministic stub defaults additionally assert return types.

package.path = package.path .. ";./?.lua"

local assert = require("tests.helpers.assert")
local mod = require("mock_api.create")

local suite = assert.suite("create")

suite:test("type Create_DisplayLink exists", function()
    assert.assertType(mod.types["Create_DisplayLink"], "table")
end)
suite:test("Create_DisplayLink exposes 10 methods", function()
    local methods = mod.types["Create_DisplayLink"]
    assert.assertHasFunction(methods, "clear")
    assert.assertHasFunction(methods, "clearLine")
    assert.assertHasFunction(methods, "getCursorPos")
    assert.assertHasFunction(methods, "getSize")
    assert.assertHasFunction(methods, "isColor")
    assert.assertHasFunction(methods, "isColour")
    assert.assertHasFunction(methods, "setCursorPos")
    assert.assertHasFunction(methods, "update")
    assert.assertHasFunction(methods, "write")
    assert.assertHasFunction(methods, "writeBytes")
end)
suite:test("Create_DisplayLink methods are callable", function()
    local methods = mod.types["Create_DisplayLink"]
    assert.assertCalls(methods["clear"])
    assert.assertCalls(methods["clearLine"])
    assert.assertCalls(methods["getCursorPos"])
    assert.assertCalls(methods["getSize"])
    assert.assertCalls(methods["isColor"])
    assert.assertCalls(methods["isColour"])
    assert.assertCalls(methods["setCursorPos"])
    assert.assertCalls(methods["update"])
    assert.assertCalls(methods["write"])
    assert.assertCalls(methods["writeBytes"])
end)
suite:test("Create_DisplayLink stub return types", function()
    local methods = mod.types["Create_DisplayLink"]
    assert.assertType(methods["isColor"](), "boolean")
    assert.assertType(methods["isColour"](), "boolean")
end)
suite:test("type Create_Frogport exists", function()
    assert.assertType(mod.types["Create_Frogport"], "table")
end)
suite:test("Create_Frogport exposes 4 methods", function()
    local methods = mod.types["Create_Frogport"]
    assert.assertHasFunction(methods, "getAddress")
    assert.assertHasFunction(methods, "getConfiguration")
    assert.assertHasFunction(methods, "setAddress")
    assert.assertHasFunction(methods, "setConfiguration")
end)
suite:test("Create_Frogport methods are callable", function()
    local methods = mod.types["Create_Frogport"]
    assert.assertCalls(methods["getAddress"])
    assert.assertCalls(methods["getConfiguration"])
    assert.assertCalls(methods["setAddress"])
    assert.assertCalls(methods["setConfiguration"])
end)
suite:test("Create_Frogport stub return types", function()
    local methods = mod.types["Create_Frogport"]
    assert.assertType(methods["getAddress"](), "string")
    assert.assertType(methods["getConfiguration"](), "string")
    assert.assertType(methods["setConfiguration"](), "boolean")
end)
suite:test("type Create_NixieTube exists", function()
    assert.assertType(mod.types["Create_NixieTube"], "table")
end)
suite:test("Create_NixieTube exposes 4 methods", function()
    local methods = mod.types["Create_NixieTube"]
    assert.assertHasFunction(methods, "setSignal")
    assert.assertHasFunction(methods, "setText")
    assert.assertHasFunction(methods, "setTextColor")
    assert.assertHasFunction(methods, "setTextColour")
end)
suite:test("Create_NixieTube methods are callable", function()
    local methods = mod.types["Create_NixieTube"]
    assert.assertCalls(methods["setSignal"])
    assert.assertCalls(methods["setText"])
    assert.assertCalls(methods["setTextColor"])
    assert.assertCalls(methods["setTextColour"])
end)
suite:test("type Create_Packager exists", function()
    assert.assertType(mod.types["Create_Packager"], "table")
end)
suite:test("Create_Packager exposes 4 methods", function()
    local methods = mod.types["Create_Packager"]
    assert.assertHasFunction(methods, "getAddress")
    assert.assertHasFunction(methods, "getPackage")
    assert.assertHasFunction(methods, "makePackage")
    assert.assertHasFunction(methods, "setAddress")
end)
suite:test("Create_Packager methods are callable", function()
    local methods = mod.types["Create_Packager"]
    assert.assertCalls(methods["getAddress"])
    assert.assertCalls(methods["getPackage"])
    assert.assertCalls(methods["makePackage"])
    assert.assertCalls(methods["setAddress"])
end)
suite:test("Create_Packager stub return types", function()
    local methods = mod.types["Create_Packager"]
    assert.assertType(methods["getAddress"](), "string")
    assert.assertType(methods["getPackage"](), "table")
    assert.assertType(methods["makePackage"](), "boolean")
end)
suite:test("type Create_Postbox exists", function()
    assert.assertType(mod.types["Create_Postbox"], "table")
end)
suite:test("Create_Postbox exposes 4 methods", function()
    local methods = mod.types["Create_Postbox"]
    assert.assertHasFunction(methods, "getAddress")
    assert.assertHasFunction(methods, "getConfiguration")
    assert.assertHasFunction(methods, "setAddress")
    assert.assertHasFunction(methods, "setConfiguration")
end)
suite:test("Create_Postbox methods are callable", function()
    local methods = mod.types["Create_Postbox"]
    assert.assertCalls(methods["getAddress"])
    assert.assertCalls(methods["getConfiguration"])
    assert.assertCalls(methods["setAddress"])
    assert.assertCalls(methods["setConfiguration"])
end)
suite:test("Create_Postbox stub return types", function()
    local methods = mod.types["Create_Postbox"]
    assert.assertType(methods["getAddress"](), "string")
    assert.assertType(methods["getConfiguration"](), "string")
    assert.assertType(methods["setConfiguration"](), "boolean")
end)
suite:test("type Create_RedstoneRequester exists", function()
    assert.assertType(mod.types["Create_RedstoneRequester"], "table")
end)
suite:test("Create_RedstoneRequester exposes 7 methods", function()
    local methods = mod.types["Create_RedstoneRequester"]
    assert.assertHasFunction(methods, "getAddress")
    assert.assertHasFunction(methods, "getConfiguration")
    assert.assertHasFunction(methods, "request")
    assert.assertHasFunction(methods, "setAddress")
    assert.assertHasFunction(methods, "setConfiguration")
    assert.assertHasFunction(methods, "setCraftingRequest")
    assert.assertHasFunction(methods, "setRequest")
end)
suite:test("Create_RedstoneRequester methods are callable", function()
    local methods = mod.types["Create_RedstoneRequester"]
    assert.assertCalls(methods["getAddress"])
    assert.assertCalls(methods["getConfiguration"])
    assert.assertCalls(methods["request"])
    assert.assertCalls(methods["setAddress"])
    assert.assertCalls(methods["setConfiguration"])
    assert.assertCalls(methods["setCraftingRequest"])
    assert.assertCalls(methods["setRequest"])
end)
suite:test("Create_RedstoneRequester stub return types", function()
    local methods = mod.types["Create_RedstoneRequester"]
    assert.assertType(methods["getAddress"](), "string")
    assert.assertType(methods["getConfiguration"](), "string")
end)
suite:test("type Create_Repackager exists", function()
    assert.assertType(mod.types["Create_Repackager"], "table")
end)
suite:test("Create_Repackager exposes 4 methods", function()
    local methods = mod.types["Create_Repackager"]
    assert.assertHasFunction(methods, "getAddress")
    assert.assertHasFunction(methods, "getPackage")
    assert.assertHasFunction(methods, "makePackage")
    assert.assertHasFunction(methods, "setAddress")
end)
suite:test("Create_Repackager methods are callable", function()
    local methods = mod.types["Create_Repackager"]
    assert.assertCalls(methods["getAddress"])
    assert.assertCalls(methods["getPackage"])
    assert.assertCalls(methods["makePackage"])
    assert.assertCalls(methods["setAddress"])
end)
suite:test("Create_Repackager stub return types", function()
    local methods = mod.types["Create_Repackager"]
    assert.assertType(methods["getAddress"](), "string")
    assert.assertType(methods["getPackage"](), "table")
    assert.assertType(methods["makePackage"](), "boolean")
end)
suite:test("type Create_Signal exists", function()
    assert.assertType(mod.types["Create_Signal"], "table")
end)
suite:test("Create_Signal exposes 6 methods", function()
    local methods = mod.types["Create_Signal"]
    assert.assertHasFunction(methods, "cycleSignalType")
    assert.assertHasFunction(methods, "getSignalType")
    assert.assertHasFunction(methods, "getState")
    assert.assertHasFunction(methods, "isForcedRed")
    assert.assertHasFunction(methods, "listBlockingTrainNames")
    assert.assertHasFunction(methods, "setForcedRed")
end)
suite:test("Create_Signal methods are callable", function()
    local methods = mod.types["Create_Signal"]
    assert.assertCalls(methods["cycleSignalType"])
    assert.assertCalls(methods["getSignalType"])
    assert.assertCalls(methods["getState"])
    assert.assertCalls(methods["isForcedRed"])
    assert.assertCalls(methods["listBlockingTrainNames"])
    assert.assertCalls(methods["setForcedRed"])
end)
suite:test("Create_Signal stub return types", function()
    local methods = mod.types["Create_Signal"]
    assert.assertType(methods["getSignalType"](), "string")
    assert.assertType(methods["getState"](), "string")
    assert.assertType(methods["isForcedRed"](), "boolean")
    assert.assertType(methods["listBlockingTrainNames"](), "table")
end)
suite:test("type Create_Station exists", function()
    assert.assertType(mod.types["Create_Station"], "table")
end)
suite:test("Create_Station exposes 16 methods", function()
    local methods = mod.types["Create_Station"]
    assert.assertHasFunction(methods, "assemble")
    assert.assertHasFunction(methods, "canTrainReach")
    assert.assertHasFunction(methods, "disassemble")
    assert.assertHasFunction(methods, "distanceTo")
    assert.assertHasFunction(methods, "getSchedule")
    assert.assertHasFunction(methods, "getStationName")
    assert.assertHasFunction(methods, "getTrainName")
    assert.assertHasFunction(methods, "hasSchedule")
    assert.assertHasFunction(methods, "isInAssemblyMode")
    assert.assertHasFunction(methods, "isTrainEnroute")
    assert.assertHasFunction(methods, "isTrainImminent")
    assert.assertHasFunction(methods, "isTrainPresent")
    assert.assertHasFunction(methods, "setAssemblyMode")
    assert.assertHasFunction(methods, "setSchedule")
    assert.assertHasFunction(methods, "setStationName")
    assert.assertHasFunction(methods, "setTrainName")
end)
suite:test("Create_Station methods are callable", function()
    local methods = mod.types["Create_Station"]
    assert.assertCalls(methods["assemble"])
    assert.assertCalls(methods["canTrainReach"])
    assert.assertCalls(methods["disassemble"])
    assert.assertCalls(methods["distanceTo"])
    assert.assertCalls(methods["getSchedule"])
    assert.assertCalls(methods["getStationName"])
    assert.assertCalls(methods["getTrainName"])
    assert.assertCalls(methods["hasSchedule"])
    assert.assertCalls(methods["isInAssemblyMode"])
    assert.assertCalls(methods["isTrainEnroute"])
    assert.assertCalls(methods["isTrainImminent"])
    assert.assertCalls(methods["isTrainPresent"])
    assert.assertCalls(methods["setAssemblyMode"])
    assert.assertCalls(methods["setSchedule"])
    assert.assertCalls(methods["setStationName"])
    assert.assertCalls(methods["setTrainName"])
end)
suite:test("Create_Station stub return types", function()
    local methods = mod.types["Create_Station"]
    assert.assertType(methods["canTrainReach"](), "table")
    assert.assertType(methods["distanceTo"](), "table")
    assert.assertType(methods["getSchedule"](), "table")
    assert.assertType(methods["getStationName"](), "string")
    assert.assertType(methods["getTrainName"](), "string")
    assert.assertType(methods["hasSchedule"](), "boolean")
    assert.assertType(methods["isInAssemblyMode"](), "boolean")
    assert.assertType(methods["isTrainEnroute"](), "boolean")
    assert.assertType(methods["isTrainImminent"](), "boolean")
    assert.assertType(methods["isTrainPresent"](), "boolean")
end)
suite:test("type Create_Sticker exists", function()
    assert.assertType(mod.types["Create_Sticker"], "table")
end)
suite:test("Create_Sticker exposes 5 methods", function()
    local methods = mod.types["Create_Sticker"]
    assert.assertHasFunction(methods, "extend")
    assert.assertHasFunction(methods, "isAttachedToBlock")
    assert.assertHasFunction(methods, "isExtended")
    assert.assertHasFunction(methods, "retract")
    assert.assertHasFunction(methods, "toggle")
end)
suite:test("Create_Sticker methods are callable", function()
    local methods = mod.types["Create_Sticker"]
    assert.assertCalls(methods["extend"])
    assert.assertCalls(methods["isAttachedToBlock"])
    assert.assertCalls(methods["isExtended"])
    assert.assertCalls(methods["retract"])
    assert.assertCalls(methods["toggle"])
end)
suite:test("Create_Sticker stub return types", function()
    local methods = mod.types["Create_Sticker"]
    assert.assertType(methods["extend"](), "boolean")
    assert.assertType(methods["isAttachedToBlock"](), "boolean")
    assert.assertType(methods["isExtended"](), "boolean")
    assert.assertType(methods["retract"](), "boolean")
    assert.assertType(methods["toggle"](), "boolean")
end)
suite:test("type Create_StockTicker exists", function()
    assert.assertType(mod.types["Create_StockTicker"], "table")
end)
suite:test("Create_StockTicker exposes 1 methods", function()
    local methods = mod.types["Create_StockTicker"]
    assert.assertHasFunction(methods, "requestFiltered")
end)
suite:test("Create_StockTicker methods are callable", function()
    local methods = mod.types["Create_StockTicker"]
    assert.assertCalls(methods["requestFiltered"])
end)
suite:test("Create_StockTicker stub return types", function()
    local methods = mod.types["Create_StockTicker"]
    assert.assertType(methods["requestFiltered"](), "number")
end)
suite:test("type Create_TableClothShop exists", function()
    assert.assertType(mod.types["Create_TableClothShop"], "table")
end)
suite:test("Create_TableClothShop exposes 7 methods", function()
    local methods = mod.types["Create_TableClothShop"]
    assert.assertHasFunction(methods, "getAddress")
    assert.assertHasFunction(methods, "getPriceTagCount")
    assert.assertHasFunction(methods, "isShop")
    assert.assertHasFunction(methods, "setAddress")
    assert.assertHasFunction(methods, "setPriceTagCount")
    assert.assertHasFunction(methods, "setPriceTagItem")
    assert.assertHasFunction(methods, "setWares")
end)
suite:test("Create_TableClothShop methods are callable", function()
    local methods = mod.types["Create_TableClothShop"]
    assert.assertCalls(methods["getAddress"])
    assert.assertCalls(methods["getPriceTagCount"])
    assert.assertCalls(methods["isShop"])
    assert.assertCalls(methods["setAddress"])
    assert.assertCalls(methods["setPriceTagCount"])
    assert.assertCalls(methods["setPriceTagItem"])
    assert.assertCalls(methods["setWares"])
end)
suite:test("Create_TableClothShop stub return types", function()
    local methods = mod.types["Create_TableClothShop"]
    assert.assertType(methods["getAddress"](), "string")
    assert.assertType(methods["getPriceTagCount"](), "number")
    assert.assertType(methods["isShop"](), "boolean")
end)
suite:test("type Create_TrainObserver exists", function()
    assert.assertType(mod.types["Create_TrainObserver"], "table")
end)
suite:test("Create_TrainObserver exposes 1 methods", function()
    local methods = mod.types["Create_TrainObserver"]
    assert.assertHasFunction(methods, "isTrainPassing")
end)
suite:test("Create_TrainObserver methods are callable", function()
    local methods = mod.types["Create_TrainObserver"]
    assert.assertCalls(methods["isTrainPassing"])
end)
suite:test("Create_TrainObserver stub return types", function()
    local methods = mod.types["Create_TrainObserver"]
    assert.assertType(methods["isTrainPassing"](), "boolean")
end)

local passed, failed = suite:summary()
return passed, failed
